<?php
/**
 * H-Code Margin Settings For All Shortcode In VC.
 *
 * @package H-Code
 */
?>
<?php

/*-----------------------------------------------------------------------------------*/
/* Brando Desktop Margin */
/*-----------------------------------------------------------------------------------*/

vc_add_shortcode_param( 'brando_custom_desktop_margin', 'brando_custom_desktop_margin_callback', BRANDO_ADDONS_ROOT_DIR . '/brando-shortcodes/js/custom.js' );
if ( ! function_exists( 'brando_custom_desktop_margin_callback' ) ) :
  function brando_custom_desktop_margin_callback( $settings, $value ) {

     $output = '';

     $brando_desktop_margin =array(
          __('Select Margin', 'brando-addons') => '',
          __('Margin 0auto', 'brando-addons') => 'margin-0auto',
          __('No Margin', 'brando-addons') => 'no-margin',
          __('No Margin Top', 'brando-addons') => 'no-margin-top',
          __('No Margin Bottom', 'brando-addons') => 'no-margin-bottom',
          __('No Margin Left', 'brando-addons') => 'no-margin-left',
          __('No Margin Right', 'brando-addons') => 'no-margin-right',
          __('No Margin Left Right', 'brando-addons') => 'no-margin-lr',
          __('No Margin Top Bottom', 'brando-addons') => 'no-margin-tb',
          __('Margin One All', 'brando-addons') => 'margin-one-all',
          __('Margin Two All', 'brando-addons') => 'margin-two-all',
          __('Margin Three All', 'brando-addons') => 'margin-three-all',
          __('Margin Four All', 'brando-addons') => 'margin-four-all',
          __('Margin Five All', 'brando-addons') => 'margin-five-all',
          __('Margin Six All', 'brando-addons') => 'margin-six-all',
          __('Margin Seven All', 'brando-addons') => 'margin-seven-all',
          __('Margin Eight All', 'brando-addons') => 'margin-eight-all',
          __('Margin Nine All', 'brando-addons') => 'margin-nine-all',
          __('Margin Ten All', 'brando-addons') => 'margin-ten-all',
          __('Margin Eleven All', 'brando-addons') => 'margin-eleven-all',
          __('Margin Twelve All', 'brando-addons') => 'margin-twelve-all',
          __('Margin Thirteen All', 'brando-addons') => 'margin-thirteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'margin-eighteen-all',
          __('Margin One Top', 'brando-addons') => 'margin-one-top',
          __('Margin Two Top', 'brando-addons') => 'margin-two-top',
          __('Margin Three Top', 'brando-addons') => 'margin-three-top',
          __('Margin Four Top', 'brando-addons') => 'margin-four-top',
          __('Margin Five Top', 'brando-addons') => 'margin-five-top',
          __('Margin Six Top', 'brando-addons') => 'margin-six-top',
          __('Margin Seven Top', 'brando-addons') => 'margin-seven-top',
          __('Margin Eight Top', 'brando-addons') => 'margin-eight-top',
          __('Margin Nine Top', 'brando-addons') => 'margin-nine-top',
          __('Margin Ten Top', 'brando-addons') => 'margin-ten-top',
          __('Margin Eleven Top', 'brando-addons') => 'margin-eleven-top',
          __('Margin Twelve Top', 'brando-addons') => 'margin-twelve-top',
          __('Margin Thirteen Top', 'brando-addons') => 'margin-thirteen-top',
          __('Margin Fourteen Top', 'brando-addons') => 'margin-fourteen-top',
          __('Margin Fifteen Top', 'brando-addons') => 'margin-fifteen-top',
          __('Margin Sixteen Top', 'brando-addons') => 'margin-sixteen-top',
          __('Margin Seventeen Top', 'brando-addons') => 'margin-seventeen-top',
          __('Margin Eighteen Top', 'brando-addons') => 'margin-eighteen-top',
          __('Margin One Bottom', 'brando-addons') => 'margin-one-bottom',
          __('Margin Two Bottom', 'brando-addons') => 'margin-two-bottom',
          __('Margin Three Bottom', 'brando-addons') => 'margin-three-bottom',
          __('Margin Four Bottom', 'brando-addons') => 'margin-four-bottom',
          __('Margin Five Bottom', 'brando-addons') => 'margin-five-bottom',
          __('Margin Six Bottom', 'brando-addons') => 'margin-six-bottom',
          __('Margin Seven Bottom', 'brando-addons') => 'margin-seven-bottom',
          __('Margin Eight Bottom', 'brando-addons') => 'margin-eight-bottom',
          __('Margin Nine Bottom', 'brando-addons') => 'margin-nine-bottom',
          __('Margin Ten Bottom', 'brando-addons') => 'margin-ten-bottom',
          __('Margin Eleven Bottom', 'brando-addons') => 'margin-eleven-bottom',
          __('Margin Twelve Bottom', 'brando-addons') => 'margin-twelve-bottom',
          __('Margin Thirteen Bottom', 'brando-addons') => 'margin-thirteen-bottom',
          __('Margin Fourteen Bottom', 'brando-addons') => 'margin-fourteen-bottom',
          __('Margin Fifteen Bottom', 'brando-addons') => 'margin-fifteen-bottom',
          __('Margin Sixteen Bottom', 'brando-addons') => 'margin-sixteen-bottom',
          __('Margin Seventeen Bottom', 'brando-addons') => 'margin-seventeen-bottom',
          __('Margin Eighteen Bottom', 'brando-addons') => 'margin-eighteen-bottom',
          __('Margin One Left', 'brando-addons') => 'margin-one-left',
          __('Margin Two Left', 'brando-addons') => 'margin-two-left',
          __('Margin Three Left', 'brando-addons') => 'margin-three-left',
          __('Margin Four Left', 'brando-addons') => 'margin-four-left',
          __('Margin Five Left', 'brando-addons') => 'margin-five-left',
          __('Margin Six Left', 'brando-addons') => 'margin-six-left',
          __('Margin Seven Left', 'brando-addons') => 'margin-seven-left',
          __('Margin Eight Left', 'brando-addons') => 'margin-eight-left',
          __('Margin Nine Left', 'brando-addons') => 'margin-nine-left',
          __('Margin Ten Left', 'brando-addons') => 'margin-ten-left',
          __('Margin Eleven Left', 'brando-addons') => 'margin-eleven-left',
          __('Margin Twelve Left', 'brando-addons') => 'margin-twelve-left',
          __('Margin Thirteen Left', 'brando-addons') => 'margin-thirteen-left',
          __('Margin Fourteen Left', 'brando-addons') => 'margin-fourteen-left',
          __('Margin Fifteen Left', 'brando-addons') => 'margin-fifteen-left',
          __('Margin Sixteen Left', 'brando-addons') => 'margin-sixteen-left',
          __('Margin Seventeen Left', 'brando-addons') => 'margin-seventeen-left',
          __('Margin Eighteen Left', 'brando-addons') => 'margin-eighteen-left',    
          __('Margin One Right', 'brando-addons') => 'margin-one-right',
          __('Margin Two Right', 'brando-addons') => 'margin-two-right',
          __('Margin Three Right', 'brando-addons') => 'margin-three-right',
          __('Margin Four Right', 'brando-addons') => 'margin-four-right',
          __('Margin Five Right', 'brando-addons') => 'margin-five-right',
          __('Margin Six Right', 'brando-addons') => 'margin-six-right',
          __('Margin Seven Right', 'brando-addons') => 'margin-seven-right',
          __('Margin Eight Right', 'brando-addons') => 'margin-eight-right',
          __('Margin Nine Right', 'brando-addons') => 'margin-nine-right',
          __('Margin Ten Right', 'brando-addons') => 'margin-ten-right',
          __('Margin Eleven Right', 'brando-addons') => 'margin-eleven-right',
          __('Margin Twelve Right', 'brando-addons') => 'margin-twelve-right',
          __('Margin Thirteen Right', 'brando-addons') => 'margin-thirteen-right',
          __('Margin Fourteen Right', 'brando-addons') => 'margin-fourteen-right',
          __('Margin Fifteen Right', 'brando-addons') => 'margin-fifteen-right',
          __('Margin Sixteen Right', 'brando-addons') => 'margin-sixteen-right',
          __('Margin Seventeen Right', 'brando-addons') => 'margin-seventeen-right',
          __('Margin Eighteen Right', 'brando-addons') => 'margin-eighteen-right',
          __('Margin One Top Bottom', 'brando-addons') => 'margin-one-tb',
          __('Margin Two Top Bottom', 'brando-addons') => 'margin-two-tb',
          __('Margin Three Top Bottom', 'brando-addons') => 'margin-three-tb',
          __('Margin Four Top Bottom', 'brando-addons') => 'margin-four-tb',
          __('Margin Five Top Bottom', 'brando-addons') => 'margin-five-tb',
          __('Margin Six Top Bottom', 'brando-addons') => 'margin-six-tb',
          __('Margin Seven Top Bottom', 'brando-addons') => 'margin-seven-tb',
          __('Margin Eight Top Bottom', 'brando-addons') => 'margin-eight-tb',
          __('Margin Nine Top Bottom', 'brando-addons') => 'margin-nine-tb',
          __('Margin Ten Top Bottom', 'brando-addons') => 'margin-ten-tb',
          __('Margin Eleven Top Bottom', 'brando-addons') => 'margin-eleven-tb',
          __('Margin Twelve Top Bottom', 'brando-addons') => 'margin-twelve-tb',
          __('Margin Thirteen Top Bottom', 'brando-addons') => 'margin-thirteen-tb',
          __('Margin Fourteen Top Bottom', 'brando-addons') => 'margin-fourteen-tb',
          __('Margin Fifteen Top Bottom', 'brando-addons') => 'margin-fifteen-tb',
          __('Margin Sixteen Top Bottom', 'brando-addons') => 'margin-sixteen-tb',
          __('Margin Seventeen Top Bottom', 'brando-addons') => 'margin-seventeen-tb',
          __('Margin Eighteen Top Bottom', 'brando-addons') => 'margin-eighteen-tb',
          __('Margin One Left Right', 'brando-addons') => 'margin-one-lr',
          __('Margin Two Left Right', 'brando-addons') => 'margin-two-lr',
          __('Margin Three Left Right', 'brando-addons') => 'margin-three-lr',
          __('Margin Four Left Right', 'brando-addons') => 'margin-four-lr',
          __('Margin Five Left Right', 'brando-addons') => 'margin-five-lr',
          __('Margin Six Left Right', 'brando-addons') => 'margin-six-lr',
          __('Margin Seven Left Right', 'brando-addons') => 'margin-seven-lr',
          __('Margin Eight Left Right', 'brando-addons') => 'margin-eight-lr',
          __('Margin Nine Left Right', 'brando-addons') => 'margin-nine-lr',
          __('Margin Ten Left Right', 'brando-addons') => 'margin-ten-lr',
          __('Margin Eleven Left Right', 'brando-addons') => 'margin-eleven-lr',
          __('Margin Twelve Left Right', 'brando-addons') => 'margin-twelve-lr',
          __('Margin Thirteen Left Right', 'brando-addons') => 'margin-thirteen-lr',
          __('Margin Fourteen Left Right', 'brando-addons') => 'margin-fourteen-lr',
          __('Margin Fifteen Left Right', 'brando-addons') => 'margin-fifteen-lr',
          __('Margin Sixteen Left Right', 'brando-addons') => 'margin-sixteen-lr',
          __('Margin Seventeen Left Right', 'brando-addons') => 'margin-seventeen-lr',
          __('Margin Eighteen Left Right', 'brando-addons') => 'margin-eighteen-lr',
          __('Margin Top 30px', 'brando-addons') => 'margin-top-30px',
          __('Margin Top 81px', 'brando-addons') => 'margin-top-81px',
          __('Margin Top 90px', 'brando-addons') => 'margin-top-90px',
          __('Margin Left Right 7px', 'brando-addons') => 'margin-lr-7px',
          __('Margin Left Right 10px', 'brando-addons') => 'margin-lr-10px',
          __('Margin Bottom 30px', 'brando-addons') => 'margin-bottom-30px',
          __('Custom', 'brando-addons') => 'custom-desktop-margin',
     );

      $output .= '<input name="' . esc_attr( $settings['param_name'] ) . '" class="wpb_vc_param_value brando-desktop-custom-margin-select-value wpb-textinput ' .
               esc_attr( $settings['param_name'] ) . ' ' .
               esc_attr( $settings['type'] ) . '_field" type="hidden" value="' . esc_attr( $value ) . '" />';

      $output .= '<select name="'. $settings['param_name']. '-custom" class="brando-desktop-custom-margin-select wpb_vc_param_value wpb-input wpb-select '. $settings['param_name']
                 . ' ' . $settings['type']
                 . '">';
      foreach ( $brando_desktop_margin as $index => $data ) {
        $output .= '<option class="" value="' . $data . '" title="'.$index.'">'.$index.'</option>';
      }
      $output .= '</select>';

    return $output;
  }
endif;


/*-----------------------------------------------------------------------------------*/
/* Brando Mini Desktop Margin */
/*-----------------------------------------------------------------------------------*/

vc_add_shortcode_param( 'brando_custom_mini_desktop_margin', 'brando_custom_mini_desktop_margin_callback', BRANDO_ADDONS_ROOT_DIR . '/brando-shortcodes/js/custom.js' );
if ( ! function_exists( 'brando_custom_mini_desktop_margin_callback' ) ) :
  function brando_custom_mini_desktop_margin_callback( $settings, $value ) {

     $output = '';

     $brando_desktop_mini_margin =array(
          __('Select Margin', 'brando-addons') => '',
          __('Margin 0auto', 'brando-addons') => 'md-margin-0auto',
          __('No Margin', 'brando-addons') => 'md-no-margin',
          __('No Margin Top', 'brando-addons') => 'md-no-margin-top',
          __('No Margin Bottom', 'brando-addons') => 'md-no-margin-bottom',
          __('No Margin Left', 'brando-addons') => 'md-no-margin-left',
          __('No Margin Right', 'brando-addons') => 'md-no-margin-right',
          __('No Margin Left Right', 'brando-addons') => 'md-no-margin-lr',
          __('No Margin Top Bottom', 'brando-addons') => 'md-no-margin-tb',
          __('Margin One All', 'brando-addons') => 'md-margin-one-all',
          __('Margin Two All', 'brando-addons') => 'md-margin-two-all',
          __('Margin Three All', 'brando-addons') => 'md-margin-three-all',
          __('Margin Four All', 'brando-addons') => 'md-margin-four-all',
          __('Margin Five All', 'brando-addons') => 'md-margin-five-all',
          __('Margin Six All', 'brando-addons') => 'md-margin-six-all',
          __('Margin Seven All', 'brando-addons') => 'md-margin-seven-all',
          __('Margin Eight All', 'brando-addons') => 'md-margin-eight-all',
          __('Margin Nine All', 'brando-addons') => 'md-margin-nine-all',
          __('Margin Ten All', 'brando-addons') => 'md-margin-ten-all',
          __('Margin Eleven All', 'brando-addons') => 'md-margin-eleven-all',
          __('Margin Twelve All', 'brando-addons') => 'md-margin-twelve-all',
          __('Margin Thirteen All', 'brando-addons') => 'md-margin-thirteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'md-margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'md-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'md-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'md-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'md-margin-eighteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'md-margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'md-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'md-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'md-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'md-margin-eighteen-all',
          __('Margin One Top', 'brando-addons') => 'md-margin-one-top',
          __('Margin Two Top', 'brando-addons') => 'md-margin-two-top',
          __('Margin Three Top', 'brando-addons') => 'md-margin-three-top',
          __('Margin Four Top', 'brando-addons') => 'md-margin-four-top',
          __('Margin Five Top', 'brando-addons') => 'md-margin-five-top',
          __('Margin Six Top', 'brando-addons') => 'md-margin-six-top',
          __('Margin Seven Top', 'brando-addons') => 'md-margin-seven-top',
          __('Margin Eight Top', 'brando-addons') => 'md-margin-eight-top',
          __('Margin Nine Top', 'brando-addons') => 'md-margin-nine-top',
          __('Margin Ten Top', 'brando-addons') => 'md-margin-ten-top',
          __('Margin Eleven Top', 'brando-addons') => 'md-margin-eleven-top',
          __('Margin Twelve Top', 'brando-addons') => 'md-margin-twelve-top',
          __('Margin Thirteen Top', 'brando-addons') => 'md-margin-thirteen-top',
          __('Margin Fourteen Top', 'brando-addons') => 'md-margin-fourteen-top',
          __('Margin Fifteen Top', 'brando-addons') => 'md-margin-fifteen-top',
          __('Margin Sixteen Top', 'brando-addons') => 'md-margin-sixteen-top',
          __('Margin Seventeen Top', 'brando-addons') => 'md-margin-seventeen-top',
          __('Margin Eighteen Top', 'brando-addons') => 'md-margin-eighteen-top',
          __('Margin One Bottom', 'brando-addons') => 'md-margin-one-bottom',
          __('Margin Two Bottom', 'brando-addons') => 'md-margin-two-bottom',
          __('Margin Three Bottom', 'brando-addons') => 'md-margin-three-bottom',
          __('Margin Four Bottom', 'brando-addons') => 'md-margin-four-bottom',
          __('Margin Five Bottom', 'brando-addons') => 'md-margin-five-bottom',
          __('Margin Six Bottom', 'brando-addons') => 'md-margin-six-bottom',
          __('Margin Seven Bottom', 'brando-addons') => 'md-margin-seven-bottom',
          __('Margin Eight Bottom', 'brando-addons') => 'md-margin-eight-bottom',
          __('Margin Nine Bottom', 'brando-addons') => 'md-margin-nine-bottom',
          __('Margin Ten Bottom', 'brando-addons') => 'md-margin-ten-bottom',
          __('Margin Eleven Bottom', 'brando-addons') => 'md-margin-eleven-bottom',
          __('Margin Twelve Bottom', 'brando-addons') => 'md-margin-twelve-bottom',
          __('Margin Thirteen Bottom', 'brando-addons') => 'md-md-margin-thirteen-bottom',
          __('Margin Fourteen Bottom', 'brando-addons') => 'md-margin-fourteen-bottom',
          __('Margin Fifteen Bottom', 'brando-addons') => 'md-margin-fifteen-bottom',
          __('Margin Sixteen Bottom', 'brando-addons') => 'md-margin-sixteen-bottom',
          __('Margin Seventeen Bottom', 'brando-addons') => 'md-margin-seventeen-bottom',
          __('Margin Eighteen Bottom', 'brando-addons') => 'md-margin-eighteen-bottom',
          __('Margin One Left', 'brando-addons') => 'md-margin-one-left',
          __('Margin Two Left', 'brando-addons') => 'md-margin-two-left',
          __('Margin Three Left', 'brando-addons') => 'md-margin-three-left',
          __('Margin Four Left', 'brando-addons') => 'md-margin-four-left',
          __('Margin Five Left', 'brando-addons') => 'md-margin-five-left',
          __('Margin Six Left', 'brando-addons') => 'md-margin-six-left',
          __('Margin Seven Left', 'brando-addons') => 'md-margin-seven-left',
          __('Margin Eight Left', 'brando-addons') => 'md-margin-eight-left',
          __('Margin Nine Left', 'brando-addons') => 'md-margin-nine-left',
          __('Margin Ten Left', 'brando-addons') => 'md-margin-ten-left',
          __('Margin Eleven Left', 'brando-addons') => 'md-margin-eleven-left',
          __('Margin Twelve Left', 'brando-addons') => 'md-margin-twelve-left',
          __('Margin Thirteen Left', 'brando-addons') => 'md-margin-thirteen-left',
          __('Margin Fourteen Left', 'brando-addons') => 'md-margin-fourteen-left',
          __('Margin Fifteen Left', 'brando-addons') => 'md-margin-fifteen-left',
          __('Margin Sixteen Left', 'brando-addons') => 'md-margin-sixteen-left',
          __('Margin Seventeen Left', 'brando-addons') => 'md-margin-seventeen-left',
          __('Margin Eighteen Left', 'brando-addons') => 'md-margin-eighteen-left',
          __('Margin One Right', 'brando-addons') => 'md-margin-one-right',
          __('Margin Two Right', 'brando-addons') => 'md-margin-two-right',
          __('Margin Three Right', 'brando-addons') => 'md-margin-three-right',
          __('Margin Four Right', 'brando-addons') => 'md-margin-four-right',
          __('Margin Five Right', 'brando-addons') => 'md-margin-five-right',
          __('Margin Six Right', 'brando-addons') => 'md-margin-six-right',
          __('Margin Seven Right', 'brando-addons') => 'md-margin-seven-right',
          __('Margin Eight Right', 'brando-addons') => 'md-margin-eight-right',
          __('Margin Nine Right', 'brando-addons') => 'md-margin-nine-right',
          __('Margin Ten Right', 'brando-addons') => 'md-margin-ten-right',
          __('Margin Eleven Right', 'brando-addons') => 'md-margin-eleven-right',
          __('Margin Twelve Right', 'brando-addons') => 'md-margin-twelve-right',
          __('Margin Thirteen Right', 'brando-addons') => 'md-margin-thirteen-right',
          __('Margin Fourteen Right', 'brando-addons') => 'md-margin-fourteen-right',
          __('Margin Fifteen Right', 'brando-addons') => 'md-margin-fifteen-right',
          __('Margin Sixteen Right', 'brando-addons') => 'md-margin-sixteen-right',
          __('Margin Seventeen Right', 'brando-addons') => 'md-margin-seventeen-right',
          __('Margin Eighteen Right', 'brando-addons') => 'md-margin-eighteen-right',
          __('Margin One Top Bottom', 'brando-addons') => 'md-margin-one-tb',
          __('Margin Two Top Bottom', 'brando-addons') => 'md-margin-two-tb',
          __('Margin Three Top Bottom', 'brando-addons') => 'md-margin-three-tb',
          __('Margin Four Top Bottom', 'brando-addons') => 'md-margin-four-tb',
          __('Margin Five Top Bottom', 'brando-addons') => 'md-margin-five-tb',
          __('Margin Six Top Bottom', 'brando-addons') => 'md-margin-six-tb',
          __('Margin Seven Top Bottom', 'brando-addons') => 'md-margin-seven-tb',
          __('Margin Eight Top Bottom', 'brando-addons') => 'md-margin-eight-tb',
          __('Margin Nine Top Bottom', 'brando-addons') => 'md-margin-nine-tb',
          __('Margin Ten Top Bottom', 'brando-addons') => 'md-margin-ten-tb',
          __('Margin Eleven Top Bottom', 'brando-addons') => 'md-margin-eleven-tb',
          __('Margin Twelve Top Bottom', 'brando-addons') => 'md-margin-twelve-tb',
          __('Margin Thirteen Top Bottom', 'brando-addons') => 'md-margin-thirteen-tb',
          __('Margin Fourteen Top Bottom', 'brando-addons') => 'md-margin-fourteen-tb',
          __('Margin Fifteen Top Bottom', 'brando-addons') => 'md-margin-fifteen-tb',
          __('Margin Sixteen Top Bottom', 'brando-addons') => 'md-margin-sixteen-tb',
          __('Margin Seventeen Top Bottom', 'brando-addons') => 'md-margin-seventeen-tb',
          __('Margin Eighteen Top Bottom', 'brando-addons') => 'md-margin-eighteen-tb',
          __('Margin One Left Right', 'brando-addons') => 'md-margin-one-lr',
          __('Margin Two Left Right', 'brando-addons') => 'md-margin-two-lr',
          __('Margin Three Left Right', 'brando-addons') => 'md-margin-three-lr',
          __('Margin Four Left Right', 'brando-addons') => 'md-margin-four-lr',
          __('Margin Five Left Right', 'brando-addons') => 'md-margin-five-lr',
          __('Margin Six Left Right', 'brando-addons') => 'md-margin-six-lr',
          __('Margin Seven Left Right', 'brando-addons') => 'md-margin-seven-lr',
          __('Margin Eight Left Right', 'brando-addons') => 'md-margin-eight-lr',
          __('Margin Nine Left Right', 'brando-addons') => 'md-margin-nine-lr',
          __('Margin Ten Left Right', 'brando-addons') => 'md-margin-ten-lr',
          __('Margin Eleven Left Right', 'brando-addons') => 'md-margin-eleven-lr',
          __('Margin Twelve Left Right', 'brando-addons') => 'md-margin-twelve-lr',
          __('Margin Thirteen Left Right', 'brando-addons') => 'md-margin-thirteen-lr',
          __('Margin Fourteen Left Right', 'brando-addons') => 'md-margin-fourteen-lr',
          __('Margin Fifteen Left Right', 'brando-addons') => 'md-margin-fifteen-lr',
          __('Margin Sixteen Left Right', 'brando-addons') => 'md-margin-sixteen-lr',
          __('Margin Seventeen Left Right', 'brando-addons') => 'md-margin-seventeen-lr',
          __('Margin Eighteen Left Right', 'brando-addons') => 'md-margin-eighteen-lr',
          __('Margin Top 30px', 'brando-addons') => 'md-margin-top-30px',
          __('Margin Top 81px', 'brando-addons') => 'md-margin-top-81px',
          __('Margin Left Right 7px', 'brando-addons') => 'md-margin-lr-7px',
          __('Margin Left Right 10px', 'brando-addons') => 'md-margin-lr-10px',
          __('Custom', 'brando-addons') => 'custom-mini-desktop-margin',
     );

      $output .= '<input name="' . esc_attr( $settings['param_name'] ) . '" class="wpb_vc_param_value brando-mini-desktop-custom-margin-select-value wpb-textinput ' .
               esc_attr( $settings['param_name'] ) . ' ' .
               esc_attr( $settings['type'] ) . '_field" type="hidden" value="' . esc_attr( $value ) . '" />';

      $output .= '<select name="'. $settings['param_name']. '-custom" class="brando-mini-desktop-custom-margin-select wpb_vc_param_value wpb-input wpb-select '. $settings['param_name']
                 . ' ' . $settings['type']
                 . '">';
      foreach ( $brando_desktop_mini_margin as $index => $data ) {
        $output .= '<option class="" value="' . $data . '" title="'.$index.'">'.$index.'</option>';
      }
      $output .= '</select>';

    return $output;
  }
endif;

/*-----------------------------------------------------------------------------------*/
/* Brando Ipad Margin */
/*-----------------------------------------------------------------------------------*/

vc_add_shortcode_param( 'brando_custom_ipad_margin', 'brando_custom_ipad_margin_callback', BRANDO_ADDONS_ROOT_DIR . '/brando-shortcodes/js/custom.js' );
if ( ! function_exists( 'brando_custom_ipad_margin_callback' ) ) :
  function brando_custom_ipad_margin_callback( $settings, $value ) {

     $output = '';

     $brando_ipad_margin =array(
          __('Select Margin', 'brando-addons') => '',
          __('Margin 0auto', 'brando-addons') => 'sm-margin-0auto',
          __('No Margin', 'brando-addons') => 'sm-no-margin',
          __('No Margin Top', 'brando-addons') => 'sm-no-margin-top',
          __('No Margin Bottom', 'brando-addons') => 'sm-no-margin-bottom',
          __('No Margin Left', 'brando-addons') => 'sm-no-margin-left',
          __('No Margin Right', 'brando-addons') => 'sm-no-margin-right',
          __('No Margin Left Right', 'brando-addons') => 'sm-no-margin-lr',
          __('No Margin Top Bottom', 'brando-addons') => 'sm-no-margin-tb',
          __('Margin One All', 'brando-addons') => 'sm-margin-one-all',
          __('Margin Two All', 'brando-addons') => 'sm-margin-two-all',
          __('Margin Three All', 'brando-addons') => 'sm-margin-three-all',
          __('Margin Four All', 'brando-addons') => 'sm-margin-four-all',
          __('Margin Five All', 'brando-addons') => 'sm-margin-five-all',
          __('Margin Six All', 'brando-addons') => 'sm-margin-six-all',
          __('Margin Seven All', 'brando-addons') => 'sm-margin-seven-all',
          __('Margin Eight All', 'brando-addons') => 'sm-margin-eight-all',
          __('Margin Nine All', 'brando-addons') => 'sm-margin-nine-all',
          __('Margin Ten All', 'brando-addons') => 'sm-margin-ten-all',
          __('Margin Eleven All', 'brando-addons') => 'sm-margin-eleven-all',
          __('Margin Twelve All', 'brando-addons') => 'sm-margin-twelve-all',
          __('Margin Thirteen All', 'brando-addons') => 'sm-margin-thirteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'sm-margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'sm-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'sm-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'sm-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'sm-margin-eighteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'sm-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'sm-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'sm-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'sm-margin-eighteen-all',
          __('Margin One Top', 'brando-addons') => 'sm-margin-one-top',
          __('Margin Two Top', 'brando-addons') => 'sm-margin-two-top',
          __('Margin Three Top', 'brando-addons') => 'sm-margin-three-top',
          __('Margin Four Top', 'brando-addons') => 'sm-margin-four-top',
          __('Margin Five Top', 'brando-addons') => 'sm-margin-five-top',
          __('Margin Six Top', 'brando-addons') => 'sm-margin-six-top',
          __('Margin Seven Top', 'brando-addons') => 'sm-margin-seven-top',
          __('Margin Eight Top', 'brando-addons') => 'sm-margin-eight-top',
          __('Margin Nine Top', 'brando-addons') => 'sm-margin-nine-top',
          __('Margin Ten Top', 'brando-addons') => 'sm-margin-ten-top',
          __('Margin Eleven Top', 'brando-addons') => 'sm-margin-eleven-top',
          __('Margin Twelve Top', 'brando-addons') => 'sm-margin-twelve-top',
          __('Margin Thirteen Top', 'brando-addons') => 'sm-margin-thirteen-top',
          __('Margin Fourteen Top', 'brando-addons') => 'sm-margin-fourteen-top',
          __('Margin Fifteen Top', 'brando-addons') => 'sm-margin-fifteen-top',
          __('Margin Sixteen Top', 'brando-addons') => 'sm-margin-sixteen-top',
          __('Margin Seventeen Top', 'brando-addons') => 'sm-margin-seventeen-top',
          __('Margin Eighteen Top', 'brando-addons') => 'sm-margin-eighteen-top',
          __('Margin One Bottom', 'brando-addons') => 'sm-margin-one-bottom',
          __('Margin Two Bottom', 'brando-addons') => 'sm-margin-two-bottom',
          __('Margin Three Bottom', 'brando-addons') => 'sm-margin-three-bottom',
          __('Margin Four Bottom', 'brando-addons') => 'sm-margin-four-bottom',
          __('Margin Five Bottom', 'brando-addons') => 'sm-margin-five-bottom',
          __('Margin Six Bottom', 'brando-addons') => 'sm-margin-six-bottom',
          __('Margin Seven Bottom', 'brando-addons') => 'sm-margin-seven-bottom',
          __('Margin Eight Bottom', 'brando-addons') => 'sm-margin-eight-bottom',
          __('Margin Nine Bottom', 'brando-addons') => 'sm-margin-nine-bottom',
          __('Margin Ten Bottom', 'brando-addons') => 'sm-margin-ten-bottom',
          __('Margin Eleven Bottom', 'brando-addons') => 'sm-margin-eleven-bottom',
          __('Margin Twelve Bottom', 'brando-addons') => 'sm-margin-twelve-bottom',
          __('Margin Thirteen Bottom', 'brando-addons') => 'sm-margin-thirteen-bottom',
          __('Margin Fourteen Bottom', 'brando-addons') => 'sm-margin-fourteen-bottom',
          __('Margin Fifteen Bottom', 'brando-addons') => 'sm-margin-fifteen-bottom',
          __('Margin Sixteen Bottom', 'brando-addons') => 'sm-margin-sixteen-bottom',
          __('Margin Seventeen Bottom', 'brando-addons') => 'sm-margin-seventeen-bottom',
          __('Margin Eighteen Bottom', 'brando-addons') => 'sm-margin-eighteen-bottom',
          __('Margin One Left', 'brando-addons') => 'sm-margin-one-left',
          __('Margin Two Left', 'brando-addons') => 'sm-margin-two-left',
          __('Margin Three Left', 'brando-addons') => 'sm-margin-three-left',
          __('Margin Four Left', 'brando-addons') => 'sm-margin-four-left',
          __('Margin Five Left', 'brando-addons') => 'sm-margin-five-left',
          __('Margin Six Left', 'brando-addons') => 'sm-margin-six-left',
          __('Margin Seven Left', 'brando-addons') => 'sm-margin-seven-left',
          __('Margin Eight Left', 'brando-addons') => 'sm-margin-eight-left',
          __('Margin Nine Left', 'brando-addons') => 'sm-margin-nine-left',
          __('Margin Ten Left', 'brando-addons') => 'sm-margin-ten-left',
          __('Margin Eleven Left', 'brando-addons') => 'sm-margin-eleven-left',
          __('Margin Twelve Left', 'brando-addons') => 'sm-margin-twelve-left',
          __('Margin Thirteen Left', 'brando-addons') => 'sm-margin-thirteen-left',
          __('Margin Fourteen Left', 'brando-addons') => 'sm-margin-fourteen-left',
          __('Margin Fifteen Left', 'brando-addons') => 'sm-margin-fifteen-left',
          __('Margin Sixteen Left', 'brando-addons') => 'sm-margin-sixteen-left',
          __('Margin Seventeen Left', 'brando-addons') => 'sm-margin-seventeen-left',
          __('Margin Eighteen Left', 'brando-addons') => 'sm-margin-eighteen-left',
          __('Margin One Right', 'brando-addons') => 'sm-margin-one-right',
          __('Margin Two Right', 'brando-addons') => 'sm-margin-two-right',
          __('Margin Three Right', 'brando-addons') => 'sm-margin-three-right',
          __('Margin Four Right', 'brando-addons') => 'sm-margin-four-right',
          __('Margin Five Right', 'brando-addons') => 'sm-margin-five-right',
          __('Margin Six Right', 'brando-addons') => 'sm-margin-six-right',
          __('Margin Seven Right', 'brando-addons') => 'sm-margin-seven-right',
          __('Margin Eight Right', 'brando-addons') => 'sm-margin-eight-right',
          __('Margin Nine Right', 'brando-addons') => 'sm-margin-nine-right',
          __('Margin Ten Right', 'brando-addons') => 'sm-margin-ten-right',
          __('Margin Eleven Right', 'brando-addons') => 'sm-margin-eleven-right',
          __('Margin Twelve Right', 'brando-addons') => 'sm-margin-twelve-right',
          __('Margin Thirteen Right', 'brando-addons') => 'sm-margin-thirteen-right',
          __('Margin Fourteen Right', 'brando-addons') => 'sm-margin-fourteen-right',
          __('Margin Fifteen Right', 'brando-addons') => 'sm-margin-fifteen-right',
          __('Margin Sixteen Right', 'brando-addons') => 'sm-margin-sixteen-right',
          __('Margin Seventeen Right', 'brando-addons') => 'sm-margin-seventeen-right',
          __('Margin Eighteen Right', 'brando-addons') => 'sm-margin-eighteen-right',
          __('Margin One Top Bottom', 'brando-addons') => 'sm-margin-one-tb',
          __('Margin Two Top Bottom', 'brando-addons') => 'sm-margin-two-tb',
          __('Margin Three Top Bottom', 'brando-addons') => 'sm-margin-three-tb',
          __('Margin Four Top Bottom', 'brando-addons') => 'sm-margin-four-tb',
          __('Margin Five Top Bottom', 'brando-addons') => 'sm-margin-five-tb',
          __('Margin Six Top Bottom', 'brando-addons') => 'sm-margin-six-tb',
          __('Margin Seven Top Bottom', 'brando-addons') => 'sm-margin-seven-tb',
          __('Margin Eight Top Bottom', 'brando-addons') => 'sm-margin-eight-tb',
          __('Margin Nine Top Bottom', 'brando-addons') => 'sm-margin-nine-tb',
          __('Margin Ten Top Bottom', 'brando-addons') => 'sm-margin-ten-tb',
          __('Margin Eleven Top Bottom', 'brando-addons') => 'sm-margin-eleven-tb',
          __('Margin Twelve Top Bottom', 'brando-addons') => 'sm-margin-twelve-tb',
          __('Margin Thirteen Top Bottom', 'brando-addons') => 'sm-margin-thirteen-tb',
          __('Margin Fourteen Top Bottom', 'brando-addons') => 'sm-margin-fourteen-tb',
          __('Margin Fifteen Top Bottom', 'brando-addons') => 'sm-margin-fifteen-tb',
          __('Margin Sixteen Top Bottom', 'brando-addons') => 'sm-margin-sixteen-tb',
          __('Margin Seventeen Top Bottom', 'brando-addons') => 'sm-margin-seventeen-tb',
          __('Margin Eighteen Top Bottom', 'brando-addons') => 'sm-margin-eighteen-tb',
          __('Margin One Left Right', 'brando-addons') => 'sm-margin-one-lr',
          __('Margin Two Left Right', 'brando-addons') => 'sm-margin-two-lr',
          __('Margin Three Left Right', 'brando-addons') => 'sm-margin-three-lr',
          __('Margin Four Left Right', 'brando-addons') => 'sm-margin-four-lr',
          __('Margin Five Left Right', 'brando-addons') => 'sm-margin-five-lr',
          __('Margin Six Left Right', 'brando-addons') => 'sm-margin-six-lr',
          __('Margin Seven Left Right', 'brando-addons') => 'sm-margin-seven-lr',
          __('Margin Eight Left Right', 'brando-addons') => 'sm-margin-eight-lr',
          __('Margin Nine Left Right', 'brando-addons') => 'sm-margin-nine-lr',
          __('Margin Ten Left Right', 'brando-addons') => 'sm-margin-ten-lr',
          __('Margin Eleven Left Right', 'brando-addons') => 'sm-margin-eleven-lr',
          __('Margin Twelve Left Right', 'brando-addons') => 'sm-margin-twelve-lr',
          __('Margin Thirteen Left Right', 'brando-addons') => 'sm-margin-thirteen-lr',
          __('Margin Fourteen Left Right', 'brando-addons') => 'sm-margin-fourteen-lr',
          __('Margin Fifteen Left Right', 'brando-addons') => 'sm-margin-fifteen-lr',
          __('Margin Sixteen Left Right', 'brando-addons') => 'sm-margin-sixteen-lr',
          __('Margin Seventeen Left Right', 'brando-addons') => 'sm-margin-seventeen-lr',
          __('Margin Eighteen Left Right', 'brando-addons') => 'sm-margin-eighteen-lr',
          __('Margin Top 30px', 'brando-addons') => 'sm-margin-top-30px',
          __('Margin Top 81px', 'brando-addons') => 'sm-margin-top-81px',
          __('Margin Top 70px', 'brando-addons') => 'sm-margin-top-70px',
          __('Margin Left Right 7px', 'brando-addons') => 'sm-margin-lr-7px',
          __('Margin Left Right 10px', 'brando-addons') => 'sm-margin-lr-10px',
          __('Custom', 'brando-addons') => 'custom-ipad-margin',
     );

      $output .= '<input name="' . esc_attr( $settings['param_name'] ) . '" class="wpb_vc_param_value brando-ipad-custom-margin-select-value wpb-textinput ' .
               esc_attr( $settings['param_name'] ) . ' ' .
               esc_attr( $settings['type'] ) . '_field" type="hidden" value="' . esc_attr( $value ) . '" />';

      $output .= '<select name="'. $settings['param_name']. '-custom" class="brando-ipad-custom-margin-select wpb_vc_param_value wpb-input wpb-select '. $settings['param_name']
                 . ' ' . $settings['type']
                 . '">';
      foreach ( $brando_ipad_margin as $index => $data ) {
        $output .= '<option class="" value="' . $data . '" title="'.$index.'">'.$index.'</option>';
      }
      $output .= '</select>';

    return $output;
  }
endif;

/*-----------------------------------------------------------------------------------*/
/* Brando Mobile Margin */
/*-----------------------------------------------------------------------------------*/

vc_add_shortcode_param( 'brando_custom_mobile_margin', 'brando_custom_mobile_margin_callback', BRANDO_ADDONS_ROOT_DIR . '/brando-shortcodes/js/custom.js' );
if ( ! function_exists( 'brando_custom_mobile_margin_callback' ) ) :
  function brando_custom_mobile_margin_callback( $settings, $value ) {

     $output = '';

     $brando_mobile_margin =array(
          __('Select Margin', 'brando-addons') => '',
          __('Margin 0auto', 'brando-addons') => 'xs-margin-0auto',
          __('No Margin', 'brando-addons') => 'xs-no-margin',
          __('No Margin Top', 'brando-addons') => 'xs-no-margin-top',
          __('No Margin Bottom', 'brando-addons') => 'xs-no-margin-bottom',
          __('No Margin Left', 'brando-addons') => 'xs-no-margin-left',
          __('No Margin Right', 'brando-addons') => 'xs-no-margin-right',
          __('No Margin Left Right', 'brando-addons') => 'xs-no-margin-lr',
          __('No Margin Top Bottom', 'brando-addons') => 'xs-no-margin-tb',
          __('Margin One All', 'brando-addons') => 'xs-margin-one-all',
          __('Margin Two All', 'brando-addons') => 'xs-margin-two-all',
          __('Margin Three All', 'brando-addons') => 'xs-margin-three-all',
          __('Margin Four All', 'brando-addons') => 'xs-margin-four-all',
          __('Margin Five All', 'brando-addons') => 'xs-margin-five-all',
          __('Margin Six All', 'brando-addons') => 'xs-margin-six-all',
          __('Margin Seven All', 'brando-addons') => 'xs-margin-seven-all',
          __('Margin Eight All', 'brando-addons') => 'xs-margin-eight-all',
          __('Margin Nine All', 'brando-addons') => 'xs-margin-nine-all',
          __('Margin Ten All', 'brando-addons') => 'xs-margin-ten-all',
          __('Margin Eleven All', 'brando-addons') => 'xs-margin-eleven-all',
          __('Margin Twelve All', 'brando-addons') => 'xs-margin-twelve-all',
          __('Margin Thirteen All', 'brando-addons') => 'xs-margin-thirteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'xs-margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'xs-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'xs-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'xs-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'xs-margin-eighteen-all',
          __('Margin Fourteen All', 'brando-addons') => 'xs-margin-fourteen-all',
          __('Margin Fifteen All', 'brando-addons') => 'xs-margin-fifteen-all',
          __('Margin Sixteen All', 'brando-addons') => 'xs-margin-sixteen-all',
          __('Margin Seventeen All', 'brando-addons') => 'xs-margin-seventeen-all',
          __('Margin Eighteen All', 'brando-addons') => 'xs-margin-eighteen-all',
          __('Margin One Top', 'brando-addons') => 'xs-margin-one-top',
          __('Margin Two Top', 'brando-addons') => 'xs-margin-two-top',
          __('Margin Three Top', 'brando-addons') => 'xs-margin-three-top',
          __('Margin Four Top', 'brando-addons') => 'xs-margin-four-top',
          __('Margin Five Top', 'brando-addons') => 'xs-margin-five-top',
          __('Margin Six Top', 'brando-addons') => 'xs-margin-six-top',
          __('Margin Seven Top', 'brando-addons') => 'xs-margin-seven-top',
          __('Margin Eight Top', 'brando-addons') => 'xs-margin-eight-top',
          __('Margin Nine Top', 'brando-addons') => 'xs-margin-nine-top',
          __('Margin Ten Top', 'brando-addons') => 'xs-margin-ten-top',
          __('Margin Eleven Top', 'brando-addons') => 'xs-margin-eleven-top',
          __('Margin Twelve Top', 'brando-addons') => 'xs-margin-twelve-top',
          __('Margin Thirteen Top', 'brando-addons') => 'xs-margin-thirteen-top',
          __('Margin Fourteen Top', 'brando-addons') => 'xs-margin-fourteen-top',
          __('Margin Fifteen Top', 'brando-addons') => 'xs-margin-fifteen-top',
          __('Margin Sixteen Top', 'brando-addons') => 'xs-margin-sixteen-top',
          __('Margin Seventeen Top', 'brando-addons') => 'xs-margin-seventeen-top',
          __('Margin Eighteen Top', 'brando-addons') => 'xs-margin-eighteen-top',
          __('Margin One Bottom', 'brando-addons') => 'xs-margin-one-bottom',
          __('Margin Two Bottom', 'brando-addons') => 'xs-margin-two-bottom',
          __('Margin Three Bottom', 'brando-addons') => 'xs-margin-three-bottom',
          __('Margin Four Bottom', 'brando-addons') => 'xs-margin-four-bottom',
          __('Margin Five Bottom', 'brando-addons') => 'xs-margin-five-bottom',
          __('Margin Six Bottom', 'brando-addons') => 'xs-margin-six-bottom',
          __('Margin Seven Bottom', 'brando-addons') => 'xs-margin-seven-bottom',
          __('Margin Eight Bottom', 'brando-addons') => 'xs-margin-eight-bottom',
          __('Margin Nine Bottom', 'brando-addons') => 'xs-margin-nine-bottom',
          __('Margin Ten Bottom', 'brando-addons') => 'xs-margin-ten-bottom',
          __('Margin Eleven Bottom', 'brando-addons') => 'xs-margin-eleven-bottom',
          __('Margin Twelve Bottom', 'brando-addons') => 'xs-margin-twelve-bottom',
          __('Margin Thirteen Bottom', 'brando-addons') => 'xs-margin-thirteen-bottom',
          __('Margin Fourteen Bottom', 'brando-addons') => 'xs-margin-fourteen-bottom',
          __('Margin Fifteen Bottom', 'brando-addons') => 'xs-margin-fifteen-bottom',
          __('Margin Sixteen Bottom', 'brando-addons') => 'xs-margin-sixteen-bottom',
          __('Margin Seventeen Bottom', 'brando-addons') => 'xs-margin-seventeen-bottom',
          __('Margin Eighteen Bottom', 'brando-addons') => 'xs-margin-eighteen-bottom',
          __('Margin One Left', 'brando-addons') => 'xs-margin-one-left',
          __('Margin Two Left', 'brando-addons') => 'xs-margin-two-left',
          __('Margin Three Left', 'brando-addons') => 'xs-margin-three-left',
          __('Margin Four Left', 'brando-addons') => 'xs-margin-four-left',
          __('Margin Five Left', 'brando-addons') => 'xs-margin-five-left',
          __('Margin Six Left', 'brando-addons') => 'xs-margin-six-left',
          __('Margin Seven Left', 'brando-addons') => 'xs-margin-seven-left',
          __('Margin Eight Left', 'brando-addons') => 'xs-margin-eight-left',
          __('Margin Nine Left', 'brando-addons') => 'xs-margin-nine-left',
          __('Margin Ten Left', 'brando-addons') => 'xs-margin-ten-left',
          __('Margin Eleven Left', 'brando-addons') => 'xs-margin-eleven-left',
          __('Margin Twelve Left', 'brando-addons') => 'xs-margin-twelve-left',
          __('Margin Thirteen Left', 'brando-addons') => 'xs-margin-thirteen-left',
          __('Margin Fourteen Left', 'brando-addons') => 'xs-margin-fourteen-left',
          __('Margin Fifteen Left', 'brando-addons') => 'xs-margin-fifteen-left',
          __('Margin Sixteen Left', 'brando-addons') => 'xs-margin-sixteen-left',
          __('Margin Seventeen Left', 'brando-addons') => 'xs-margin-seventeen-left',
          __('Margin Eighteen Left', 'brando-addons') => 'xs-margin-eighteen-left',
          __('Margin One Right', 'brando-addons') => 'xs-margin-one-right',
          __('Margin Two Right', 'brando-addons') => 'xs-margin-two-right',
          __('Margin Three Right', 'brando-addons') => 'xs-margin-three-right',
          __('Margin Four Right', 'brando-addons') => 'xs-margin-four-right',
          __('Margin Five Right', 'brando-addons') => 'xs-margin-five-right',
          __('Margin Six Right', 'brando-addons') => 'xs-margin-six-right',
          __('Margin Seven Right', 'brando-addons') => 'xs-margin-seven-right',
          __('Margin Eight Right', 'brando-addons') => 'xs-margin-eight-right',
          __('Margin Nine Right', 'brando-addons') => 'xs-margin-nine-right',
          __('Margin Ten Right', 'brando-addons') => 'xs-margin-ten-right',
          __('Margin Eleven Right', 'brando-addons') => 'xs-margin-eleven-right',
          __('Margin Twelve Right', 'brando-addons') => 'xs-margin-twelve-right',
          __('Margin Thirteen Right', 'brando-addons') => 'xs-margin-thirteen-right',
          __('Margin Fourteen Right', 'brando-addons') => 'xs-margin-fourteen-right',
          __('Margin Fifteen Right', 'brando-addons') => 'xs-margin-fifteen-right',
          __('Margin Sixteen Right', 'brando-addons') => 'xs-margin-sixteen-right',
          __('Margin Seventeen Right', 'brando-addons') => 'xs-margin-seventeen-right',
          __('Margin Eighteen Right', 'brando-addons') => 'xs-margin-eighteen-right',
          __('Margin One Top Bottom', 'brando-addons') => 'xs-margin-one-tb',
          __('Margin Two Top Bottom', 'brando-addons') => 'xs-margin-two-tb',
          __('Margin Three Top Bottom', 'brando-addons') => 'xs-margin-three-tb',
          __('Margin Four Top Bottom', 'brando-addons') => 'xs-margin-four-tb',
          __('Margin Five Top Bottom', 'brando-addons') => 'xs-margin-five-tb',
          __('Margin Six Top Bottom', 'brando-addons') => 'xs-margin-six-tb',
          __('Margin Seven Top Bottom', 'brando-addons') => 'xs-margin-seven-tb',
          __('Margin Eight Top Bottom', 'brando-addons') => 'xs-margin-eight-tb',
          __('Margin Nine Top Bottom', 'brando-addons') => 'xs-margin-nine-tb',
          __('Margin Ten Top Bottom', 'brando-addons') => 'xs-margin-ten-tb',
          __('Margin Eleven Top Bottom', 'brando-addons') => 'xs-margin-eleven-tb',
          __('Margin Twelve Top Bottom', 'brando-addons') => 'xs-margin-twelve-tb',
          __('Margin Thirteen Top Bottom', 'brando-addons') => 'xs-margin-thirteen-tb',
          __('Margin Fourteen Top Bottom', 'brando-addons') => 'xs-margin-fourteen-tb',
          __('Margin Fifteen Top Bottom', 'brando-addons') => 'xs-margin-fifteen-tb',
          __('Margin Sixteen Top Bottom', 'brando-addons') => 'xs-margin-sixteen-tb',
          __('Margin Seventeen Top Bottom', 'brando-addons') => 'xs-margin-seventeen-tb',
          __('Margin Eighteen Top Bottom', 'brando-addons') => 'xs-margin-eighteen-tb',
          __('Margin One Left Right', 'brando-addons') => 'xs-margin-one-lr',
          __('Margin Two Left Right', 'brando-addons') => 'xs-margin-two-lr',
          __('Margin Three Left Right', 'brando-addons') => 'xs-margin-three-lr',
          __('Margin Four Left Right', 'brando-addons') => 'xs-margin-four-lr',
          __('Margin Five Left Right', 'brando-addons') => 'xs-margin-five-lr',
          __('Margin Six Left Right', 'brando-addons') => 'xs-margin-six-lr',
          __('Margin Seven Left Right', 'brando-addons') => 'xs-margin-seven-lr',
          __('Margin Eight Left Right', 'brando-addons') => 'xs-margin-eight-lr',
          __('Margin Nine Left Right', 'brando-addons') => 'xs-margin-nine-lr',
          __('Margin Ten Left Right', 'brando-addons') => 'xs-margin-ten-lr',
          __('Margin Eleven Left Right', 'brando-addons') => 'xs-margin-eleven-lr',
          __('Margin Twelve Left Right', 'brando-addons') => 'xs-margin-twelve-lr',
          __('Margin Thirteen Left Right', 'brando-addons') => 'xs-margin-thirteen-lr',
          __('Margin Fourteen Left Right', 'brando-addons') => 'xs-margin-fourteen-lr',
          __('Margin Fifteen Left Right', 'brando-addons') => 'xs-margin-fifteen-lr',
          __('Margin Sixteen Left Right', 'brando-addons') => 'xs-margin-sixteen-lr',
          __('Margin Seventeen Left Right', 'brando-addons') => 'xs-margin-seventeen-lr',
          __('Margin Eighteen Left Right', 'brando-addons') => 'xs-margin-eighteen-lr',
          __('Margin Top 30px', 'brando-addons') => 'xs-margin-top-30px',
          __('Margin Top 81px', 'brando-addons') => 'xs-margin-top-81px',
          __('Margin Left Right 7px', 'brando-addons') => 'xs-margin-lr-7px',
          __('Margin Left Right 10px', 'brando-addons') => 'xs-margin-lr-10px',
          __('Custom', 'brando-addons') => 'custom-mobile-margin',
     );

      $output .= '<input name="' . esc_attr( $settings['param_name'] ) . '" class="wpb_vc_param_value brando-mobile-custom-margin-select-value wpb-textinput ' .
               esc_attr( $settings['param_name'] ) . ' ' .
               esc_attr( $settings['type'] ) . '_field" type="hidden" value="' . esc_attr( $value ) . '" />';

      $output .= '<select name="'. $settings['param_name']. '-custom" class="brando-mobile-custom-margin-select wpb_vc_param_value wpb-input wpb-select '. $settings['param_name']
                 . ' ' . $settings['type']
                 . '">';
      foreach ( $brando_mobile_margin as $index => $data ) {
        $output .= '<option class="" value="' . $data . '" title="'.$index.'">'.$index.'</option>';
      }
      $output .= '</select>';

    return $output;
  }
endif;