<?php
/**
 * Map For Section Heading
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Section Heading */
/*-----------------------------------------------------------------------------------*/

$heading_class = 'brando_heading_'.time() . '-2-' . rand( 0, 100 );
vc_map( array(
  'name' => __('Section Heading', 'brando-addons'),
  'description' => __( 'Add styled section heading', 'brando-addons' ),  
  'icon' => 'fa fa-header brando-shortcode-icon',
  'base' => 'brando_section_heading',
  'category' => 'Brando',
  'params' => array(
    array(
      'type' => 'hidden',
      'heading' => __('Text', 'brando-addons' ),
      'param_name' => 'brando_token_class',
      'value' => $heading_class,
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Heading Style', 'brando-addons'),
      'param_name' => 'brando_heading_type',
      'value' => array(__('Select Heading Style', 'brando-addons') => '',
                       __('Heading Style1', 'brando-addons') => 'heading-style1',
                       __('Heading Style2', 'brando-addons') => 'heading-style2',
                       __('Heading Style3', 'brando-addons') => 'heading-style3',
                       __('Heading Style4', 'brando-addons') => 'heading-style4',
                       __('Heading Style5', 'brando-addons') => 'heading-style5',
                       __('Heading Style6', 'brando-addons') => 'heading-style6',
                       __('Heading Style7', 'brando-addons') => 'heading-style7',
                       __('Heading Style8', 'brando-addons') => 'heading-style8',
                       __('Heading Style9', 'brando-addons') => 'heading-style9',
                       __('Heading Style10', 'brando-addons') => 'heading-style10',
                       __('Heading Style11', 'brando-addons') => 'heading-style11',
                       __('Heading Style12', 'brando-addons') => 'heading-style12',
                       __('Heading Style13', 'brando-addons') => 'heading-style13',
                       __('Heading Style14', 'brando-addons') => 'heading-style14',
                      ),
      ),
    array(
      'type' => 'brando_preview_image',
      'heading' => __('Select pre-made style for Heading', 'brando-addons'),
      'param_name' => 'heading_preview_image',
      'admin_label' => true,
      'value' => array(__('Select Heading Type', 'brando-addons') => '',
                       __('Heading Style1', 'brando-addons') => 'heading-style1',
                       __('Heading Style2', 'brando-addons') => 'heading-style2',
                       __('Heading Style3', 'brando-addons') => 'heading-style3',
                       __('Heading Style4', 'brando-addons') => 'heading-style4',
                       __('Heading Style5', 'brando-addons') => 'heading-style5',
                       __('Heading Style6', 'brando-addons') => 'heading-style6',
                       __('Heading Style7', 'brando-addons') => 'heading-style7',
                       __('Heading Style8', 'brando-addons') => 'heading-style8',
                       __('Heading Style9', 'brando-addons') => 'heading-style9',
                       __('Heading Style10', 'brando-addons') => 'heading-style10',
                       __('Heading Style11', 'brando-addons') => 'heading-style11',
                       __('Heading Style12', 'brando-addons') => 'heading-style12',
                       __('Heading Style13', 'brando-addons') => 'heading-style13',
                       __('Heading Style14', 'brando-addons') => 'heading-style14',
                      ),
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Heading Tag', 'brando-addons'),
      'param_name' => 'brando_heading_tag',
      'value' => array(__('Select Heading Tag', 'brando-addons') => '',
                       __('h1', 'brando-addons') => 'h1',
                       __('h2', 'brando-addons') => 'h2',
                       __('h3', 'brando-addons') => 'h3',
                       __('h4', 'brando-addons') => 'h4',
                       __('h5', 'brando-addons') => 'h5',
                       __('h6', 'brando-addons') => 'h6',
                       __('span', 'brando-addons') => 'span',
                       __('p', 'brando-addons') => 'p',
                       __('div', 'brando-addons') => 'div',
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4') ),
      'group' => 'Heading Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Heading Title', 'brando-addons'),
      'param_name' => 'brando_heading',
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style2','heading-style7','heading-style4','heading-style8') ),
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Text Color', 'brando-addons'),
      'param_name' => 'brando_text_color',
      'value' => array(__('Select Text Color', 'brando-addons') => '',
                       __('Black', 'brando-addons') => 'black-text',
                       __('White', 'brando-addons') => 'white-text',
                       __('Custom', 'brando-addons') => 'custom',
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Heading Style',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Text Color', 'brando-addons' ),
      'param_name' => 'brando_heading_text_color',
      'dependency' => array( 'element' => 'brando_text_color', 'value' => array('custom') ),
      'group' => 'Heading Style',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Separator Color', 'brando-addons' ),
      'param_name' => 'brando_heading_separator_color',
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style4','heading-style8') ),
      'group' => 'Heading Style',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Left Border Color', 'brando-addons' ),
      'param_name' => 'brando_heading_left_border_color',
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style7','heading-style11') ),
      'group' => 'Heading Style',
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Enable Separator', 'brando-addons'),
      'param_name' => 'brando_enable_seperator',
      'value' => array(__('No','brando-addons') => '0', 
                       __('Yes','brando-addons') => '1'
                      ),
      'dependency'  => array( 'element' => 'brando_heading_type', 'value' => array('heading-style2','heading-style12','heading-style14')),
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Separator Color', 'brando-addons' ),
      'param_name' => 'brando_sep_color',
      'dependency' => array( 'element' => 'brando_enable_seperator', 'value' => array('1') ),
    ),  
    array(
      'type' => 'textfield',
      'heading' => __('Separator Height', 'brando-addons' ),
      'param_name' => 'separator_height',
      'dependency' => array( 'element' => 'brando_enable_seperator', 'value' => array('1') ),
      'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Required Padding Setting?', 'brando-addons'),
      'param_name' => 'padding_setting',
      'value' => array(__('No', 'brando-addons') => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_desktop_padding',
      'param_name' => 'desktop_padding',
      'heading' => __('Padding (For Desktop Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Padding (For Desktop Device)', 'brando-addons' ),
      'param_name' => 'custom_desktop_padding',
      'dependency' => array( 'element' => 'desktop_padding', 'value' => array('custom-desktop-padding') ),
      'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_ipad_padding',
      'param_name' => 'ipad_padding',
      'heading' => __('Padding (For iPad Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Padding (For iPad Device)', 'brando-addons' ),
      'param_name' => 'custom_ipad_padding',
      'dependency' => array( 'element' => 'ipad_padding', 'value' => array('custom-ipad-padding') ),
      'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_mobile_padding',
      'param_name' => 'mobile_padding',
      'heading' => __('Padding (For Mobile Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Padding (For Mobile Device)', 'brando-addons' ),
      'param_name' => 'custom_mobile_padding',
      'dependency' => array( 'element' => 'mobile_padding', 'value' => array('custom-mobile-padding') ),
      'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'heading' => __('Required Margin Setting?', 'brando-addons'),
      'param_name' => 'margin_setting',
      'value' => array(__('No', 'brando-addons')  => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_desktop_margin',
      'param_name' => 'desktop_margin',
      'heading' => __('Margin (For Desktop Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Margin (For Desktop Device)', 'brando-addons' ),
      'param_name' => 'custom_desktop_margin',
      'dependency' => array( 'element' => 'desktop_margin', 'value' => array('custom-desktop-margin') ),
      'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_ipad_margin',
      'param_name' => 'ipad_margin',
      'heading' => __('Margin (For iPad Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Margin (For iPad Device)', 'brando-addons'),
      'param_name' => 'custom_ipad_margin',
      'dependency' => array( 'element' => 'ipad_margin', 'value' => array('custom-ipad-margin') ),
      'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'brando_custom_mobile_margin',
      'param_name' => 'mobile_margin',
      'heading' => __('Margin (For Mobile Device)', 'brando-addons' ),
      'value' => '',
      'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Margin (For Mobile Device)', 'brando-addons'),
      'param_name' => 'custom_mobile_margin',
      'dependency' => array( 'element' => 'mobile_margin', 'value' => array('custom-mobile-margin') ),
      'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Font Size', 'brando-addons' ),
      'param_name' => 'font_size',
      'description' => __( 'Define font size like 12px', 'brando-addons' ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Line Height', 'brando-addons' ),
      'param_name' => 'line_height',
      'description' => __( 'Define line height like 20px', 'brando-addons' ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'dropdown',
      'param_name' => 'font_weight',
      'heading' => __('Font Weight', 'brando-addons' ),
      'value' => array(__('Select Font Weight', 'brando-addons') => '', 
                       __('Font weight 300', 'brando-addons') => '300',
                       __('Font weight 400', 'brando-addons') => '400',
                       __('Font weight 500', 'brando-addons') => '500',
                       __('Font weight 600', 'brando-addons') => '600',
                       __('Font weight 700', 'brando-addons') => '700',
                       __('Font weight 800', 'brando-addons') => '800',
                       __('Font weight 900', 'brando-addons') => '900',
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type' => 'dropdown',
      'param_name' => 'text_transform',
      'heading' => __('Text Transform', 'brando-addons' ),
      'value' => array(__('Select Text Transform', 'brando-addons') => '', 
                       __('None', 'brando-addons') => 'none',
                       __('Uppercase', 'brando-addons') => 'uppercase',
                       __('Lowercase', 'brando-addons') => 'lowercase',
                       __('Capitalize', 'brando-addons') => 'capitalize',
                      ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style2','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Css Style',
    ),
    array(
      'type'        => 'responsive_font_settings',
      'param_name'  => 'title_settings',
      'heading'     => esc_html__( 'Font Settings For Heading Title', 'hcode-addons' ),
      'dependency' => array( 'element' => 'brando_heading_type', 'value' => array('heading-style1','heading-style3','heading-style5','heading-style6','heading-style9','heading-style10','heading-style11','heading-style12','heading-style14','heading-style13','heading-style2','heading-style7','heading-style4','heading-style8') ),
      'group' => 'Font Settings',
      'hide_font_settings_element_lg' => array('line-height','font-size','font-transform'),

    ),
    $brando_vc_extra_id,
    $brando_vc_extra_class,
    )
) );