<?php
/**
 * Map For Portfolio
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Portfolio */
/*-----------------------------------------------------------------------------------*/

$portfolio_class = 'brando_portfolio_'.time() . '-2-' . rand( 0, 100 );
$portfolio_padding_class = 'brando_portfolio_padding_'.time() . '-2-' . rand( 0, 100 );
vc_map( array(
  'name' => __('Portfolio', 'brando-addons'),
  'description' => __( 'Place portfolio items list', 'brando-addons' ),
  'icon' => 'fa fa-briefcase brando-shortcode-icon',
  'base' => 'brando_portfolio',
  'category' => 'Brando',
  'params' => array(
      array(
        'type' => 'hidden',
        'heading' => __('Text', 'brando-addons' ),
        'param_name' => 'brando_token_class',
        'value' => $portfolio_class,
      ),
      array(
        'type' => 'hidden',
        'heading' => __('Text', 'brando-addons' ),
        'param_name' => 'brando_padding_token_class',
        'value' => $portfolio_padding_class,
      ),
      array(
          'type' => 'dropdown',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Portfolio Style', 'brando-addons'),
          'param_name' => 'brando_portfolio_style',
          'value' => array(__('Select Portfolio Style', 'brando-addons') => '',
                           __('Style 1', 'brando-addons') => 'portfolio-style-1',
                           __('Style 2', 'brando-addons') => 'portfolio-style-2',
                           __('Style 3', 'brando-addons') => 'portfolio-style-3',
                           __('Style 4', 'brando-addons') => 'portfolio-style-4',
                           __('Style 5', 'brando-addons') => 'portfolio-style-5',
                           __('Style 6', 'brando-addons') => 'portfolio-style-6',
                           __('Style 7', 'brando-addons') => 'portfolio-style-7',
          ),
      ),
      array(
          'type' => 'brando_preview_image',
          'heading' => __('Select pre-made style', 'brando-addons'),
          'param_name' => 'slider_portfolio_preview_image',
          'admin_label' => true,
          'value' => array(__('Portfolio Type', 'brando-addons') => '',
                           __('Style 1', 'brando-addons') => 'portfolio-style-1',
                           __('Style 2', 'brando-addons') => 'portfolio-style-2',
                           __('Style 3', 'brando-addons') => 'portfolio-style-3',
                           __('Style 4', 'brando-addons') => 'portfolio-style-4',
                           __('Style 5', 'brando-addons') => 'portfolio-style-5',
                           __('Style 6', 'brando-addons') => 'portfolio-style-6',
                           __('Style 7', 'brando-addons') => 'portfolio-style-7',
                          ),
          ),
      array(
          'type' => 'dropdown',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Column Type', 'brando-addons'),
          'param_name' => 'brando_portfolio_columns',
          'value' => array(__('Select Column Type', 'brando-addons') => '',
                           __('2 Columns', 'brando-addons') => '2',
                           __('3 Columns', 'brando-addons') => '3',
                           __('4 Columns', 'brando-addons') => '4',
                           __('5 Columns', 'brando-addons') => '5',
          ),
          'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
      ),
      array(
          'type' => 'dropdown',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Portfolio Type', 'brando-addons'),
          'param_name' => 'brando_portfolio_type',
          'value' => array(__('Select Portfolio Type', 'brando-addons') => '',
                           __('Gutter', 'brando-addons') => 'gutter',
                           __('Gutter Medium', 'brando-addons') => 'gutter-medium',
                           __('Gutter Wide', 'brando-addons') => 'gutter-wide',
          ),
          'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
      ),
      array(
          'type' => 'brando_multiple_portfolio_categories',
          'heading' => __('Select Categories', 'brando-addons'),
          'param_name' => 'brando_categories_list',
          'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
      ),
      array(
            'type' => 'brando_custom_switch_option',
            'heading' => __('Show Title', 'brando-addons'),
            'param_name' => 'brando_show_title',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
            'group' => 'Settings',
      ),
      array(
            'type' => 'brando_custom_switch_option',
            'heading' => __('Show Subtitle', 'brando-addons'),
            'param_name' => 'brando_show_subtitle',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6') ),
            'group' => 'Settings',
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Separator', 'brando-addons'),
        'param_name' => 'brando_show_separator',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select YES to show Separator', 'brando-addons' ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-6') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Separator Color', 'brando-addons' ),
        'param_name' => 'brando_sep_color',
        'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
        'group' => 'Settings',
      ),  
      array(
        'type' => 'textfield',
        'heading' => __('Separator Height', 'brando-addons' ),
        'param_name' => 'separator_height',
        'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
        'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
        'group' => 'Settings',
      ),
      array(
          'type' => 'dropdown',
          'heading' => __('Opacity', 'brando-addons'),
          'param_name' => 'brando_opacity',
          'admin_label' => true,
          'value' => array(__('Select Opacity', 'brando-addons') => '',
                           __('0.0', 'brando-addons') => '0.0',
                           __('0.1', 'brando-addons') => '0.1',
                           __('0.2', 'brando-addons') => '0.2',
                           __('0.3', 'brando-addons') => '0.3',
                           __('0.4', 'brando-addons') => '0.4',
                           __('0.5', 'brando-addons') => '0.5',
                           __('0.6', 'brando-addons') => '0.6',
                           __('0.7', 'brando-addons') => '0.7',
                           __('0.8', 'brando-addons') => '0.8',
                           __('0.9', 'brando-addons') => '0.9',
                           __('1.0', 'brando-addons') => '1.0',
                          ),
          'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
          'group' => 'Settings',
      ), 
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Button', 'brando-addons'),
        'param_name' => 'brando_show_button',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select YES to show button', 'brando-addons' ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-2') ),
        'group' => 'Settings',
      ),
      array(
        'type'        => 'textfield',
        'heading'     => __('Button Text', 'brando-addons' ),
        'param_name'  => 'button_text',
        'admin_label' => true,
        'dependency' => array( 'element' => 'brando_show_button', 'value' => array('1') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Load more Button', 'brando-addons'),
        'param_name' => 'brando_show_load_more_button',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'std' => '0',
        'description' => __( 'Load More feature will be visible and work in ALL filter mode only.', 'brando-addons' ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Settings',
      ),
      array(
        'type'        => 'textfield',
        'heading'     => __('Load More Button Text', 'brando-addons' ),
        'param_name'  => 'load_more_button_text',
        'admin_label' => true,
        "value" => __( 'Load More', 'brando-addons' ),
        'dependency' => array( 'element' => 'brando_show_load_more_button', 'value' => array('1') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'dropdown',
        'heading' => __( 'Display Items Order by', 'brando-addons' ),
        'param_name' => 'orderby',
        'value' => array(__('Select Order by', 'brando-addons') => '',
                         __( 'Date', 'brando-addons' ) => 'date',
                         __( 'ID', 'brando-addons' ) => 'ID',
                         __( 'Author', 'brando-addons' ) => 'author',
                         __( 'Title', 'brando-addons' ) => 'title',
                         __( 'Modified', 'brando-addons' ) => 'modified',
                         __( 'Random', 'brando-addons' ) => 'rand',
                         __( 'Comment count', 'brando-addons' ) => 'comment_count',
                         __( 'Menu order', 'brando-addons' ) => 'menu_order',
                        ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Order'
      ),
      array(
        'type' => 'dropdown',
        'heading' => __( 'Display Items Sort by', 'brando-addons' ),
        'param_name' => 'order',
        'value' => array(__('Select Sort by', 'brando-addons') => '',
                         __( 'Descending', 'brando-addons' ) => 'DESC',
                         __( 'Ascending', 'brando-addons' ) => 'ASC',
                        ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Order'
      ),
      array(
        'type' => 'textfield',
        'heading' => __('No. of Post to Display', 'brando-addons'),
        'param_name' => 'brando_post_per_page',
        'value'     => '15',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Enable Lightbox Popup', 'brando-addons'),
        'param_name' => 'brando_enable_lightbox',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'holder' => 'div',
        'class' => '',
        'heading' => __('Required Padding Setting?', 'brando-addons'),
        'param_name' => 'padding_setting',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_desktop_padding',
        'param_name' => 'desktop_padding',
        'heading' => __('Padding (For Desktop Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Padding (For Desktop Device)', 'brando-addons' ),
        'param_name' => 'custom_desktop_padding',
        'dependency' => array( 'element' => 'desktop_padding', 'value' => array('custom-desktop-padding') ),
        'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_mini_desktop_padding',
        'param_name' => 'desktop_mini_padding',
        'heading' => __('Padding (For Desktop Mini Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Padding (For Mini Desktop Device)', 'brando-addons' ),
        'param_name' => 'custom_mini_desktop_padding',
        'dependency' => array( 'element' => 'desktop_mini_padding', 'value' => array('custom-mini-desktop-padding') ),
        'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_ipad_padding',
        'param_name' => 'ipad_padding',
        'heading' => __('Padding (For iPad Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Padding (For iPad Device)', 'brando-addons' ),
        'param_name' => 'custom_ipad_padding',
        'dependency' => array( 'element' => 'ipad_padding', 'value' => array('custom-ipad-padding') ),
        'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_mobile_padding',
        'param_name' => 'mobile_padding',
        'heading' => __('Padding (For Mobile Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Padding (For Mobile Device)', 'brando-addons' ),
        'param_name' => 'custom_mobile_padding',
        'dependency' => array( 'element' => 'mobile_padding', 'value' => array('custom-mobile-padding') ),
        'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'holder' => 'div',
        'class' => '',
        'heading' => __('Required Margin Setting?', 'brando-addons'),
        'param_name' => 'margin_setting',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_desktop_margin',
        'param_name' => 'desktop_margin',
        'heading' => __('Margin (For Desktop Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Margin (For Desktop Device)', 'brando-addons' ),
        'param_name' => 'custom_desktop_margin',
        'dependency' => array( 'element' => 'desktop_margin', 'value' => array('custom-desktop-margin') ),
        'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_mini_desktop_margin',
        'param_name' => 'desktop_mini_margin',
        'heading' => __('Margin (For Desktop Mini Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Margin (For Mini Desktop Device)', 'brando-addons' ),
        'param_name' => 'custom_mini_desktop_margin',
        'dependency' => array( 'element' => 'desktop_mini_margin', 'value' => array('custom-mini-desktop-margin') ),
        'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_ipad_margin',
        'param_name' => 'ipad_margin',
        'heading' => __('Margin (For iPad Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Margin (For iPad Device)', 'brando-addons'),
        'param_name' => 'custom_ipad_margin',
        'dependency' => array( 'element' => 'ipad_margin', 'value' => array('custom-ipad-margin') ),
        'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'brando_custom_mobile_margin',
        'param_name' => 'mobile_margin',
        'heading' => __('Margin (For Mobile Device)', 'brando-addons' ),
        'value' => '',
        'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
        'group' => 'Style',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Custom Margin (For Mobile Device)', 'brando-addons'),
        'param_name' => 'custom_mobile_margin',
        'dependency' => array( 'element' => 'mobile_margin', 'value' => array('custom-mobile-margin') ),
        'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
        'group' => 'Style',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Title Color', 'brando-addons' ),
        'param_name' => 'brando_title_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Subtitle Color', 'brando-addons' ),
        'param_name' => 'brando_subtitle_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Separator Color', 'brando-addons' ),
        'param_name' => 'brando_separator_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-4') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Separator Color', 'brando-addons' ),
        'param_name' => 'brando_portfolio_separator_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-7') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Hover Background Color', 'brando-addons' ),
        'param_name' => 'brando_hover_background_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Border Color', 'brando-addons' ),
        'param_name' => 'brando_border_color',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Button BG Color', 'brando-addons' ),
        'param_name' => 'brando_button_bg_color',
        'dependency' => array( 'element' => 'brando_show_button', 'value' => array('1') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Button Text Color', 'brando-addons' ),
        'param_name' => 'brando_button_text_color',
        'dependency' => array( 'element' => 'brando_show_button', 'value' => array('1') ),
        'group' => 'Color Settings',
      ),
      array(
        'type' => 'dropdown',
        'param_name' => 'brando_animation_style',
        'heading' => __('Animation Style', 'brando-addons' ),
        'value' => brando_animation_style(),
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Animation',
      ),
      array(
        'type' => 'dropdown',
        'heading' => __('Image Thumbnail Size', 'brando-addons'),
        'param_name' => 'brando_image_srcset',
        'value' => brando_image_size(),
        'std' => 'full',
        'dependency' => array( 'element' => 'brando_portfolio_style', 'value' => array('portfolio-style-1','portfolio-style-2','portfolio-style-3','portfolio-style-4','portfolio-style-5','portfolio-style-6','portfolio-style-7') ),
        'group' => 'Image',
      ),
      $brando_vc_extra_id,
      $brando_vc_extra_class,
  )
) );