<?php
/**
 * Map For Content Block
 *
 * @package Brando
 */
?>
<?php

/*-----------------------------------------------------------------------------------*/
/* Special Content Block */
/*-----------------------------------------------------------------------------------*/

$content_block_class = 'brando_content_block_'.time() . '-2-' . rand( 0, 100 );
vc_map( array(
      'name' => __( 'Special Content Block', 'brando-addons' ),
      'base' => 'brando_content_block',
      'category' => 'Brando',
      'icon' => 'fa fa-list-alt brando-shortcode-icon',
      'description' => __( 'Create a special content block', 'brando-addons' ),
      'params' => array(
        array(
          'type' => 'dropdown',
          'heading' => __('Content Block Style', 'brando-addons'),
          'param_name' => 'brando_block_premade_style',
          'value' => array(__('Select Content Block Style', 'brando-addons') => '',
                           __('Block Style1', 'brando-addons') => 'block-1',
                           __('Block Style2', 'brando-addons') => 'block-2',
                           __('Block Style3', 'brando-addons') => 'block-3',
                           __('Block Style4', 'brando-addons') => 'block-4',
                           __('Block Style5', 'brando-addons') => 'block-5',
                           __('Block Style6', 'brando-addons') => 'block-6',
                           __('Block Style7', 'brando-addons') => 'block-7',
                           __('Block Style8', 'brando-addons') => 'block-8',
                           __('Block Style9', 'brando-addons') => 'block-9',
                           __('Block Style10', 'brando-addons') => 'block-10',
                           __('Block Style11', 'brando-addons') => 'block-11',
                           __('Block Style12', 'brando-addons') => 'block-12',
                           __('Block Style13', 'brando-addons') => 'block-13',
                           __('Block Style14', 'brando-addons') => 'block-14',
                           __('Block Style15', 'brando-addons') => 'block-15',
                           __('Block Style16', 'brando-addons') => 'block-16',
                           __('Block Style17', 'brando-addons') => 'block-17',
                           __('Block Style18', 'brando-addons') => 'block-18',
                           __('Block Style19', 'brando-addons') => 'block-19',
                           __('Block Style20', 'brando-addons') => 'block-20',
                           __('Block Style21', 'brando-addons') => 'block-21',
                           __('Block Style22', 'brando-addons') => 'block-22',
                          ),
        ),
        array(
          'type' => 'brando_preview_image',
          'heading' => __('Select pre-made style for block', 'brando-addons'),
          'param_name' => 'brando_block_preview_image',
          'admin_label' => true,
          'value' => array(__('Block image', 'brando-addons') => '',
                           __('Block Style1', 'brando-addons') => 'block-1',
                           __('Block Style2', 'brando-addons') => 'block-2',
                           __('Block Style3', 'brando-addons') => 'block-3',
                           __('Block Style4', 'brando-addons') => 'block-4',
                           __('Block Style5', 'brando-addons') => 'block-5',
                           __('Block Style6', 'brando-addons') => 'block-6',
                           __('Block Style7', 'brando-addons') => 'block-7',
                           __('Block Style8', 'brando-addons') => 'block-8',
                           __('Block Style9', 'brando-addons') => 'block-9',
                           __('Block Style10', 'brando-addons') => 'block-10',
                           __('Block Style11', 'brando-addons') => 'block-11',
                           __('Block Style12', 'brando-addons') => 'block-12',
                           __('Block Style13', 'brando-addons') => 'block-13',
                           __('Block Style14', 'brando-addons') => 'block-14',
                           __('Block Style15', 'brando-addons') => 'block-15',
                           __('Block Style16', 'brando-addons') => 'block-16',
                           __('Block Style17', 'brando-addons') => 'block-17',
                           __('Block Style18', 'brando-addons') => 'block-18',
                           __('Block Style19', 'brando-addons') => 'block-19',
                           __('Block Style20', 'brando-addons') => 'block-20',
                           __('Block Style21', 'brando-addons') => 'block-21',
                           __('Block Style22', 'brando-addons') => 'block-22',
                          ),
        ),
        array(
          'type' => 'hidden',
          'heading' => __('Text', 'brando-addons' ),
          'param_name' => 'brando_token_class',
          'value' => $content_block_class,
        ),
        array(
          'type' => 'attach_image',
          'heading' => __( 'Image', 'brando-addons' ),
          'param_name' => 'brando_image',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-8','block-12','block-13','block-19','block-22') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Custom Icon', 'brando-addons'),
          'param_name' => 'custom_icon',
          'value' => array(__('NO', 'brando-addons') => '0',
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-2') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Icon Image', 'brando-addons'),
          'param_name' => 'custom_icon_image',
          'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
        ),
        array(
          'type'        => 'brando_icon',
          'heading'     => __('Font Awesome Icon', 'brando-addons' ),
          'param_name'  => 'brando_font_awesome',
          'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Custom Icon', 'brando-addons'),
          'param_name' => 'etline_custom_icon',
          'value' => array(__('NO', 'brando-addons') => '0',
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-7','block-14') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Icon Image', 'brando-addons'),
          'param_name' => 'etline_custom_icon_image',
          'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
        ),
        array(
          'type'        => 'brando_etline_icon',
          'heading'     => __('Icon', 'brando-addons' ),
          'param_name'  => 'brando_icon',
          'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '0' ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Number', 'brando-addons' ),
          'param_name'  => 'brando_number',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-15','block-21','block-10') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Small Title', 'brando-addons' ),
          'param_name'  => 'brando_small_title',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-18') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Title', 'brando-addons' ),
          'param_name'  => 'brando_title',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-1','block-2','block-4','block-6','block-7','block-8','block-9','block-11','block-12','block-13','block-14','block-15','block-16','block-17','block-18','block-19','block-20','block-21','block-22') ),
        ),
        array(
          'type'        => 'textarea',
          'heading'     => __('Subtitle', 'brando-addons' ),
          'param_name'  => 'brando_subtitle',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-8','block-9','block-16','block-18','block-19','block-20') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __( 'Separator Image', 'brando-addons' ),
          'param_name' => 'brando_sep_image',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-8') ),
        ),
      array(
          'type' => 'dropdown',
          'heading' => __( 'Select Contact Form', 'brando-addons' ),
          'param_name' => 'contact_forms_shortcode',
          'value' => $contact_forms,
          'description' => __( 'Choose previously created contact form from the drop down list.', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-11') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Discount Text', 'brando-addons' ),
          'param_name'  => 'brando_dis_text',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-6') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Year', 'brando-addons' ),
          'param_name'  => 'brando_year_text',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-16') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Link (full url with http)', 'brando-addons' ),
          'param_name'  => 'brando_link',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-2','block-4','block-6','block-8','block-9','block-15','block-16','block-17','block-21','block-22') ),
        ),
        array(
          'type'        => 'dropdown',
          'heading'     => __('Link Target', 'brando-addons' ),
          'param_name'  => 'brando_link_target',
          'value' => array(__('Self', 'brando-addons') => '_self', 
                           __('New tab / window', 'brando-addons') => '_blank'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-2','block-4','block-6','block-8','block-9','block-15','block-16','block-17','block-21','block-22') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Enable StrikeThrough', 'brando-addons'),
          'param_name' => 'brando_enable_strike_throught',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'std' => '1',
          'dependency' => array( 'element' => 'brando_block_premade_style', 'value' => array('block-13') ),
      ),
        array(
          'type' => 'textarea_html',
          'holder' => 'div',
          'heading' => __( 'Content', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-1','block-4','block-7','block-8','block-9','block-14','block-15','block-16','block-17','block-18','block-19','block-21','block-22','block-10') ),
          'param_name' => 'content',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Scroll To Section', 'brando-addons'),
          'param_name' => 'brando_scroll_to_section',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show scroll to section icon', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_block_premade_style', 'value' => array('block-8') ),
      ),
      array(
          'type' => 'textfield',
          'heading' => __('Scroll to section Id', 'brando-addons'),
          'description' => __( 'Define section id like #about', 'brando-addons' ),
          'param_name' => 'brando_section_id',
          'dependency' => array( 'element' => 'brando_scroll_to_section', 'value' => array('1') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Enable border', 'brando-addons'),
          'param_name' => 'brando_enable_border',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show border', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_block_premade_style', 'value' => array('block-8','block-18') ),
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Image Position', 'brando-addons'),
          'param_name' => 'image_position',
          'value' => array(__('Right', 'brando-addons') => '0', 
                           __('Left', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-8') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Enable Separator', 'brando-addons'),
          'param_name' => 'enable_separator',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-9','block-17','block-21') ),
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Separator Color', 'brando-addons' ),
          'param_name' => 'brando_sep_color',
          'dependency' => array( 'element' => 'enable_separator', 'value' => array('1') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Separator Height', 'brando-addons' ),
          'param_name' => 'brando_seperator_height',
          'value'     => '2px',
          'dependency' => array( 'element' => 'enable_separator', 'value' => array('1') ),
          'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Content Position', 'brando-addons'),
          'param_name' => 'content_position',
          'value' => array(__('Right', 'brando-addons') => '0', 
                           __('Left', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4') ),
        ),
        array(
          'type'        => 'vc_link',
          'heading'     => __('Button Configuration', 'brando-addons' ),
          'param_name'  => 'button_config',
          'admin_label' => true,
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-12','block-13','block-18','block-19') ),
        ),
        array(
          'type'        => 'vc_link',
          'heading'     => __('Second Button Configuration', 'brando-addons' ),
          'param_name'  => 'second_button_config',
          'admin_label' => true,
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-19') ),
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Select Icon Size', 'brando-addons'),
          'param_name' => 'icon_size',
          'admin_label' => true,
          'value' => array(__('Default', 'brando-addons') => '',
                           __('Extra Large', 'brando-addons') => 'icon-extra-large', 
                           __('Large', 'brando-addons') => 'icon-large',
                           __('Medium', 'brando-addons') => 'icon-medium',
                           __('Small', 'brando-addons') => 'icon-small',
                           __('Extra Small', 'brando-addons') => 'icon-extra-small',
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-2','block-7','block-14') ),
          'group' => 'Configuration',
        ),
        array(
          'type' => 'dropdown',
          'param_name' => 'text_transform',
          'heading' => __('Text Transform', 'brando-addons' ),
          'value' => array(__('Select Text Transform', 'brando-addons') => '', 
                           __('None', 'brando-addons') => 'none',
                           __('Uppercase', 'brando-addons') => 'text-uppercase',
                           __('Lowercase', 'brando-addons') => 'text-lowercase',
                           __('Capitalize', 'brando-addons') => 'text-capitalize',
                          ),
          'std' => 'text-uppercase',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-7') ),
          'group' => 'Configuration',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Detailbox BG Color', 'brando-addons' ),
          'param_name' => 'brando_detailbox_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Subtitle BG Color', 'brando-addons' ),
          'param_name' => 'brando_subtitle_bg_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Title Color', 'brando-addons' ),
          'param_name' => 'brando_title_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-1','block-2','block-4','block-6','block-7','block-8','block-9','block-11','block-12','block-13','block-14','block-15','block-16','block-17','block-18','block-19','block-21','block-22') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Subtitle Color', 'brando-addons' ),
          'param_name' => 'brando_subtitle_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-8','block-9','block-16','block-18','block-19') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Discount Text BG Color', 'brando-addons' ),
          'param_name' => 'brando_discount_text_bg_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-6') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Discount Text Color', 'brando-addons' ),
          'param_name' => 'brando_discount_text_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-6') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Icon Color', 'brando-addons' ),
          'param_name' => 'brando_icon_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-2','block-7','block-14') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Border Color', 'brando-addons' ),
          'param_name' => 'brando_border_color',
          'dependency'  => array( 'element' => 'brando_enable_border', 'value' => array('1') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Border Color', 'brando-addons' ),
          'param_name' => 'brando_tattoo_border_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-19') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Separator Color', 'brando-addons' ),
          'param_name' => 'brando_separator_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-12') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Block Hover Border Color', 'brando-addons' ),
          'param_name' => 'brando_block_hover_border_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-13') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Border Color', 'brando-addons' ),
          'param_name' => 'brando_block_border_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-16') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Employee Year Color', 'brando-addons' ),
          'param_name' => 'brando_block_year_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-16') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Employee Year BG Color', 'brando-addons' ),
          'param_name' => 'brando_block_year_bg_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-16') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Button BG Color', 'brando-addons' ),
          'param_name' => 'brando_block_button_bg_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-12','block-18') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Button Text Color', 'brando-addons' ),
          'param_name' => 'brando_block_button_text_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-12','block-13','block-18') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( ' Button Border Color', 'brando-addons' ),
          'param_name' => 'brando_block_button_border_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-18') ),
          'group' => 'Color',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'title_settings',
            'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
            'group' => 'Font Settings',
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-1','block-2','block-4','block-5','block-6','block-7','block-8','block-9','block-11','block-12','block-13','block-14','block-15','block-16','block-17','block-18','block-19','block-20','block-21','block-22') ),
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'subtitle_settings',
            'heading'     => esc_html__( 'Font Settings For Sub Title', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-8','block-9','block-16','block-18','block-19','block-20') ),
            'group' => 'Font Settings',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'year_settings',
            'heading'     => esc_html__( 'Font Settings For Year Text', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-16') ),
            'group' => 'Font Settings',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'number_settings',
            'heading'     => esc_html__( 'Font Settings For Number', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3','block-5','block-10','block-15','block-21') ),
            'hide_font_settings_element_lg' => array('text-align','font-transform'),
            'hide_font_settings_element_md' => array('text-align','font-transform'),
            'hide_font_settings_element_sm' => array('text-align','font-transform'),
            'hide_font_settings_element_xs' => array('text-align','font-transform'),
            'group' => 'Font Settings',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'email_settings',
            'heading'     => esc_html__( 'Font Settings For Email Id', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3','block-19') ),
            'group' => 'Font Settings',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'discount_settings',
            'heading'     => esc_html__( 'Font Settings For Discount Text', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-6') ),
            'group' => 'Font Settings',
        ),
        array(
            'type'        => 'responsive_font_settings',
            'param_name'  => 'smalltitle_settings',
            'heading'     => esc_html__( 'Font Settings For Small Title', 'hcode-addons' ),
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-18') ),
            'group' => 'Font Settings',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Phone Number', 'brando-addons' ),
          'param_name'  => 'brando_phno',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Phone Custom Icon', 'brando-addons'),
          'param_name' => 'phone_etline_custom_icon',
          'value' => array(__('NO', 'brando-addons') => '0',
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Phone Custom Icon Image', 'brando-addons'),
          'param_name' => 'phone_etline_custom_icon_image',
          'dependency' => array( 'element' => 'phone_etline_custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
        ),
        array(
          'type'        => 'brando_etline_icon',
          'heading'     => __('Phone Icon', 'brando-addons' ),
          'param_name'  => 'brando_phno_icon',
          'dependency' => array( 'element' => 'phone_etline_custom_icon', 'value' => '0' ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Email Id', 'brando-addons' ),
          'param_name'  => 'brando_email',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3','block-19') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Email Custom Icon', 'brando-addons'),
          'param_name' => 'email_etline_custom_icon',
          'value' => array(__('NO', 'brando-addons') => '0',
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-3') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Email Custom Icon Image', 'brando-addons'),
          'param_name' => 'email_etline_custom_icon_image',
          'dependency' => array( 'element' => 'email_etline_custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
        ),
        array(
          'type'        => 'brando_etline_icon',
          'heading'     => __('Email Icon', 'brando-addons' ),
          'param_name'  => 'brando_email_icon',
          'dependency' => array( 'element' => 'email_etline_custom_icon', 'value' => '0' ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Number 1', 'brando-addons' ),
          'param_name'  => 'brando_number1',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Text 1', 'brando-addons' ),
          'param_name'  => 'brando_text1',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Number 2', 'brando-addons' ),
          'param_name'  => 'brando_number2',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Text 2', 'brando-addons' ),
          'param_name'  => 'brando_text2',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Number 3', 'brando-addons' ),
          'param_name'  => 'brando_number3',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Text 3', 'brando-addons' ),
          'param_name'  => 'brando_text3',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Number 4', 'brando-addons' ),
          'param_name'  => 'brando_number4',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Text 4', 'brando-addons' ),
          'param_name'  => 'brando_text4',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Number Color', 'brando-addons' ),
          'param_name' => 'brando_number_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5','block-15','block-21','block-10') ),
          'group' => 'Color',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Text Color', 'brando-addons' ),
          'param_name' => 'brando_text_color',
          'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-5') ),
          'group' => 'Color',
        ),
        array(
            'type' => 'dropdown',
            'heading' => __('Image Thumbnail Size', 'brando-addons'),
            'param_name' => 'brando_image_srcset',
            'value' => brando_image_size(),
            'std' => 'full',
            'dependency'  => array( 'element' => 'brando_block_premade_style', 'value' => array('block-4','block-6','block-12','block-13','block-19') ),
            'group' => 'Image',
        ),
        $brando_vc_extra_id,
        $brando_vc_extra_class,
)));