<?php
/**
 * Map For Blog
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Blog */
/*-----------------------------------------------------------------------------------*/
$blog_class = 'brando_blog_'.time() . '-2-' . rand( 0, 100 );    
vc_map( array(
    'name' => __('Blog List', 'brando-addons'),
    'description' => __( 'Create a blog list', 'brando-addons' ),    
    'icon' => 'brando-shortcode-icon fa fa-list',
    'base' => 'brando_blog',
    'category' => 'Brando',
    'params' => array(
      array(
        'type' => 'hidden',
        'heading' => __('Text', 'brando-addons' ),
        'param_name' => 'brando_token_class',
        'value' => $blog_class,
      ),
      array(
        'type' => 'dropdown',
        'heading' => __('Style', 'brando-addons'),
        'param_name' => 'brando_blog_premade_style',
        'value' => array(__('Please Select Style', 'brando-addons') => '',
                         __('Style 1', 'brando-addons') => 'blog-style-1',
                         __('Style 2', 'brando-addons') => 'blog-style-2',
                         __('Style 3', 'brando-addons') => 'blog-style-3',
                         __('Modern', 'brando-addons') =>  'blog-style-4',
                         __('Grid', 'brando-addons') =>  'blog-style-5',
                        ),
      ),
      array(
        'type' => 'brando_preview_image',
        'heading' => __('Select pre-made style', 'brando-addons'),
        'param_name' => 'slider_filter_preview_image',
        'admin_label' => true,
        'value' => array(__('Blog Type', 'brando-addons') => '',
                          __('Style 1', 'brando-addons') => 'blog-style-1',
                          __('Style 2', 'brando-addons') => 'blog-style-2',
                          __('Style 3', 'brando-addons') => 'blog-style-3',
                          __('Modern', 'brando-addons') =>  'blog-style-4',
                          __('Grid', 'brando-addons') =>  'blog-style-5',
                        ),
      ),
      array(
      'type' => 'dropdown',
      'heading' => __('Column Type', 'brando-addons'),
      'param_name' => 'blog_column',
      'value' => array(__('Select Column Type', 'brando-addons') => '',
                       __('2 columns', 'brando-addons') => '2',
                       __('3 columns', 'brando-addons') => '3',
                       __('4 columns', 'brando-addons') => '4',
                      ),
      'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-5') ),
    ),
      array(
        'type' => 'brando_multiple_select_option',
        'heading' => __('Categories', 'brando-addons'),
        'param_name' => 'brando_categories_list',
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
      ),
      array(
        'type' => 'textfield',
        'heading' => __('No. of Posts per Page', 'brando-addons'),
        'description' => __( 'Enter numeric value like 8', 'brando-addons' ),
        'param_name' => 'brando_post_per_page',
        'value'     => '15',
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Post Number', 'brando-addons'),
        'param_name' => 'brando_show_post_number',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select YES to show post number', 'brando-addons' ),
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Separator', 'brando-addons'),
        'param_name' => 'brando_show_separator',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select YES to show post title', 'brando-addons' ),
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-2','blog-style-4','blog-style-5') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Separator Color', 'brando-addons' ),
        'param_name' => 'brando_sep_color',
        'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
        'group' => 'Settings',
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Separator Height', 'brando-addons' ),
        'param_name' => 'brando_seperator_height',
        'value'     => '2px',
        'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
        'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
        'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Title', 'brando-addons'),
          'param_name' => 'brando_show_post_title',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post title', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Thumbnail', 'brando-addons'),
          'param_name' => 'brando_show_post_thumbnail',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post thumbnail', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Post Featured Image Only', 'brando-addons'),
          'param_name' => 'brando_show_post_feature_image',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post feature image', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_show_post_thumbnail', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Author', 'brando-addons'),
          'param_name' => 'brando_show_post_author',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show post date', 'brando-addons' ),
          'std' => '1',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-3','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Date', 'brando-addons'),
          'param_name' => 'brando_show_post_date',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show post date', 'brando-addons' ),
          'std' => '1',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type'        => 'textfield',
          'heading'     => __('Day Format', 'brando-addons' ),
          'param_name'  => 'brando_day_format',
          'description' => wp_kses( 'Day format should be like dd, <a target="_blank" href="https://codex.wordpress.org/Formatting_Date_and_Time">click here</a> to see other date formates', 'brando-addons' ),
          'value'     => 'd m Y',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-3','blog-style-4') ),
          'group' => 'Settings',
      ),
      array(
          'type'        => 'textfield',
          'heading'     => __('Date Format', 'brando-addons' ),
          'param_name'  => 'brando_date_format',
          'description' => wp_kses( 'Date format should be like mm/dd/yyyy, <a target="_blank" href="https://codex.wordpress.org/Formatting_Date_and_Time">click here</a> to see other date formates', 'brando-addons' ),
          'value'     => 'd m Y',
          'dependency'  => array( 'element' => 'brando_show_post_date', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Excerpt', 'brando-addons'),
          'param_name' => 'brando_show_excerpt',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show excerpt, no to show full content', 'brando-addons' ),
          'std'         => '1',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-4','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type'        => 'textfield',
          'heading'     => __('Excerpt Length', 'brando-addons' ),
          'description' => __( 'Enter numeric value like 20', 'brando-addons' ),
          'param_name'  => 'brando_excerpt_length',
          'value'     => '15',
          'dependency'  => array( 'element' => 'brando_show_excerpt', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Content', 'brando-addons'),
          'param_name' => 'brando_show_content',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select content to show blog content', 'brando-addons' ),
          'std'         => '1',
          'dependency'  => array( 'element' => 'brando_show_excerpt', 'value' => array('0') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Social Icon', 'brando-addons'),
          'param_name' => 'brando_show_icon',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show social icon', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-4') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Facebook', 'brando-addons'),
          'param_name' => 'brando_show_facebook',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_show_icon', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Twitter', 'brando-addons'),
          'param_name' => 'brando_show_twitter',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_show_icon', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Google Plus', 'brando-addons'),
          'param_name' => 'brando_show_gplus',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_show_icon', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('LinkedIn', 'brando-addons'),
          'param_name' => 'brando_show_linkedin',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_show_icon', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'textarea_raw_html',
          'heading' => __( 'Custom Icon & Link Code', 'brando-addons' ),
          'param_name' => 'brando_blog_custom_link',
          'dependency'  => array( 'element' => 'brando_show_icon', 'value' => array('1') ),
          'group' => 'Settings',
        ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Like', 'brando-addons'),
          'param_name' => 'brando_show_like',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show like', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Comment', 'brando-addons'),
          'param_name' => 'brando_show_comment',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show comment', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-4') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Pagination', 'brando-addons'),
          'param_name' => 'brando_show_post_pagination',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post pagination', 'brando-addons' ),
          'std' => '1',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Settings',
      ),
      array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Button', 'brando-addons'),
          'param_name' => 'brando_show_button',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show button', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-4') ),
          'group' => 'Settings',
      ),
      array(
          'type'        => 'textfield',
          'heading'     => __('Button Text', 'brando-addons' ),
          'param_name'  => 'brando_button_text',
          'dependency'  => array( 'element' => 'brando_show_button', 'value' => array('1') ),
          'group' => 'Settings',
      ),
      array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'title_settings',
          'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array('element' => 'brando_show_post_title', 'value' => array('1'))
      ),
      array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'postmeta_font_settings',
          'heading'     => esc_html__( 'Font Settings For Post Meta', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array('element' => 'brando_show_post_title', 'value' => array('1'))
      ),
      array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'number_settings',
          'heading'     => esc_html__( 'Font Settings For Number', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array('element' => 'brando_blog_premade_style', 'value' => array('blog-style-1')),
          'hide_font_settings_element_lg' => array('text-align','font-transform'),
          'hide_font_settings_element_md' => array('text-align','font-transform'),
          'hide_font_settings_element_sm' => array('text-align','font-transform'),
          'hide_font_settings_element_xs' => array('text-align','font-transform'),
      ),
      array(
          'type' => 'dropdown',
          'heading' => __( 'Display Items Order by', 'brando-addons' ),
          'param_name' => 'orderby',
          'value' => array(__('Select Order by', 'brando-addons') => '',
                           __( 'Date', 'brando-addons' ) => 'date',
                           __( 'ID', 'brando-addons' ) => 'ID',
                           __( 'Author', 'brando-addons' ) => 'author',
                           __( 'Title', 'brando-addons' ) => 'title',
                           __( 'Modified', 'brando-addons' ) => 'modified',
                           __( 'Random', 'brando-addons' ) => 'rand',
                           __( 'Comment count', 'brando-addons' ) => 'comment_count',
                           __( 'Menu order', 'brando-addons' ) => 'menu_order',
                          ),
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
        'group' => 'Order',
      ),
      array(
        'type' => 'dropdown',
        'heading' => __( 'Display Items Sort by', 'brando-addons' ),
        'param_name' => 'order',
        'value' => array(__('Select Sort by', 'brando-addons') => '',
                         __( 'Descending', 'brando-addons' ) => 'DESC',
                         __( 'Ascending', 'brando-addons' ) => 'ASC',
                        ),
        'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
        'group' => 'Order',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Title Color', 'brando-addons' ),
          'param_name' => 'brando_title_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5')),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Title Hover Color', 'brando-addons' ),
          'param_name' => 'brando_title_hover_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Post Meta Color', 'brando-addons' ),
          'param_name' => 'brando_post_meta_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-2','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Post Meta Hover Color', 'brando-addons' ),
          'param_name' => 'brando_post_meta_hover_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1','blog-style-3','blog-style-4','blog-style-5') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Number/Date Background Color', 'brando-addons' ),
          'param_name' => 'brando_number_bg_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1', 'blog-style-4') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Number Color', 'brando-addons' ),
          'param_name' => 'brando_number_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Number Hover Color', 'brando-addons' ),
          'param_name' => 'brando_number_hover_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-1') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Day Color', 'brando-addons' ),
          'param_name' => 'brando_day_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-3','blog-style-4') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Date Color', 'brando-addons' ),
          'param_name' => 'brando_date_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-3','blog-style-4') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Border Color', 'brando-addons' ),
          'param_name' => 'brando_border_color',
          'dependency'  => array( 'element' => 'brando_blog_premade_style', 'value' => array('blog-style-3') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'dropdown',
          'heading' => __('Image Thumbnail Size', 'brando-addons'),
          'param_name' => 'brando_image_srcset',
          'value' => brando_image_size(),
          'std' => 'full',
          'group' => 'Image',
      ),
      $brando_vc_extra_id,
      $brando_vc_extra_class,
    ),
) );