<?php
/**
 * Map For Column
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Vc_inner_column change Start */
/*-----------------------------------------------------------------------------------*/

$inner_column_class = 'brando_inner_column_'.time() . '-2-' . rand( 0, 100 );
vc_map( 
  array(
      'name' => __( 'Inner Column' , 'brando-addons' ),
      'base' => 'vc_column_inner',
      'description' => 'Place content elements inside the column',
      'icon' => 'fa fa-columns brando-shortcode-icon',
      'is_container' => true,
      'content_element' => false,
      'category' => 'Brando',
      'js_view' => 'VcColumnView',
      'params' => array(
          array(
            'type' => 'hidden',
            'heading' => __('Text', 'brando-addons' ),
            'param_name' => 'brando_token_class',
            'value' => $inner_column_class,
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'column_style',
            'heading' => __( 'Please Select Column Style','brando-addons' ),
            'value' => array(__('Please select Column Style', 'brando-addons') => '',
                             __('Color', 'brando-addons') => 'color',
                             __('Image', 'brando-addons') => 'image',
                            ),
          ),
          array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Background Color', 'brando-addons' ),
            'param_name' => 'column_bg_color',
            'dependency' => array( 'element' => 'column_style', 'value' => array('color') ),
          ),
          array(
            'type' => 'attach_image',
            'heading' => __( 'Background Image', 'brando-addons' ),
            'param_name' => 'column_bg_image',
            'dependency' => array( 'element' => 'column_style', 'value' => array('image') ),
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Image With Border', 'brando-addons'),
            'param_name' => 'column_image_border',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
           'dependency' => array( 'element' => 'column_style', 'value' => array('image','color') ),
          ),
          array(
            'type' => 'colorpicker',
            'heading' => __( 'Border Color', 'brando-addons' ),
            'param_name' => 'column_image_border_color',
            'dependency' => array( 'element' => 'column_image_border', 'value' => array('1') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'column_image_type',
            'heading' => __( 'Background Image Type', 'brando-addons' ),
            'value' => array(__('Select Background Image Type', 'brando-addons') => '',
                             __('Parallax', 'brando-addons') => 'parallax',
                             __('Background Image', 'brando-addons') => 'background-image',
                            ),
            'dependency' => array( 'element' => 'column_style', 'value' => array('image') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'column_bg_image_type', 
            'heading' => __( 'Background Property', 'brando-addons' ),
            'value' => array(__('Select Background Property', 'brando-addons') => '',
                             __('Fix Background', 'brando-addons') => 'fix-background',
                             __('Cover Background', 'brando-addons') => 'cover-background',
                             __('Fill Background', 'brando-addons') => 'fill',
                            ),
            'dependency' => array( 'element' => 'column_image_type', 'value' => array('background-image') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'column_parallax_image_type',
            'heading' => __('Parallax Type', 'brando-addons' ),
            'value' => array(__('no parallax', 'brando-addons') => '',
                             __('Parallax1', 'brando-addons') => 'parallax1',
                             __('Parallax2', 'brando-addons') => 'parallax2',
                             __('Parallax3', 'brando-addons') => 'parallax3',
                             __('Parallax4', 'brando-addons') => 'parallax4',
                             __('Parallax5', 'brando-addons') => 'parallax5',
                             __('Parallax6', 'brando-addons') => 'parallax6',
                             __('Parallax7', 'brando-addons') => 'parallax7',
                             __('Parallax8', 'brando-addons') => 'parallax8',
                             __('Parallax9', 'brando-addons') => 'parallax9',
                             __('Parallax10', 'brando-addons') => 'parallax10',
                             __('Parallax11', 'brando-addons') => 'parallax11',
                             __('Parallax12', 'brando-addons') => 'parallax12',
                            ),
            'dependency' => array( 'element' => 'column_image_type', 'value' => array('parallax') ),
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Centralized Div', 'brando-addons'),
            'param_name' => 'centralized_div',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'description' => __( 'Select Yes to show div in center of column', 'brando-addons' ),
          ),
          array(
                'type' => 'brando_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => __('Overlay Div', 'brando-addons'),
                'param_name' => 'show_overlay',
                'value' => array(__('OFF', 'brando-addons') => '0', 
                                 __('ON', 'brando-addons') => '1'
                                ),
                'dependency' => array( 'element' => 'column_style', 'value' => array('image') ),
                'description' => __( 'Select ON to show overlay in column', 'brando-addons' ),
                'group' => 'Opacity',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'brando_overlay_opacity',
            'heading' => __('Overlay Opacity', 'brando-addons'),
            'value' => array(__('no opacity', 'brando-addons') => '',
                             __('0.1', 'brando-addons') => '0.1',
                             __('0.2', 'brando-addons') => '0.2',
                             __('0.3', 'brando-addons') => '0.3',
                             __('0.4', 'brando-addons') => '0.4',
                             __('0.5', 'brando-addons') => '0.5',
                             __('0.6', 'brando-addons') => '0.6',
                             __('0.7', 'brando-addons') => '0.7',
                             __('0.8', 'brando-addons') => '0.8',
                             __('0.9', 'brando-addons') => '0.9',
                             __('1.0', 'brando-addons') => '1.0',
                            ),
            'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
            'group' => 'Opacity',
          ),
          array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Overlay Color', 'brando-addons' ),
            'param_name' => 'brando_column_overlay_color',
            'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
            'group' => 'Opacity',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Alignment Setting', 'brando-addons'),
            'param_name' => 'alignment_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'description' => __( 'Select Yes to set div in alignment of column', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_alignment',
            'heading' => __('Alignment (For Desktop Device)', 'brando-addons' ),
            'value' => array(__('No Align', 'brando-addons') => '',
                             __('Left Align', 'brando-addons') => 'text-left',
                             __('Right Align', 'brando-addons') => 'text-right',
                             __('Center Align', 'brando-addons') => 'text-center',
                            ),
            'dependency' => array( 'element' => 'alignment_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_mini_alignment',
            'heading' => __('Alignment (For Desktop Mini Device)', 'brando-addons' ),
            'value' => array(__('No Align', 'brando-addons') => '',
                             __('Left Align', 'brando-addons') => 'md-text-left',
                             __('Right Align', 'brando-addons') => 'md-text-right',
                             __('Center Align', 'brando-addons') => 'md-text-center',
                            ),
            'dependency' => array( 'element' => 'alignment_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'ipad_alignment',
            'heading' => __('Alignment (For iPad/Tablet Device)', 'brando-addons' ),
            'value' => array(__('No Align', 'brando-addons') => '',
                             __('Left Align', 'brando-addons') => 'sm-text-left',
                             __('Right Align', 'brando-addons') => 'sm-text-right',
                             __('Center Align', 'brando-addons') => 'sm-text-center',
                            ),
            'dependency' => array( 'element' => 'alignment_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'mobile_alignment',
            'heading' => __('Alignment (For Mobile Device)', 'brando-addons' ),
            'value' => array(__('No Align', 'brando-addons') => '',
                             __('Left Align', 'brando-addons') => 'xs-text-left',
                             __('Right Align', 'brando-addons') => 'xs-text-right',
                             __('Center Align', 'brando-addons') => 'xs-text-center',
                            ),
            'dependency' => array( 'element' => 'alignment_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Border Setting', 'brando-addons'),
            'param_name' => 'border_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'description' => __( 'Select Yes to set div border.', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Border (For Desktop Device)', 'brando-addons'),
            'param_name' => 'desktop_show_border',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'border_setting', 'value' => array('1') ),
            'description' => __( 'Select Yes to set border in Desktop Device.', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_border_type',
            'heading' => __('Border (For Desktop Device)', 'brando-addons' ),
            'value' => array(__('Select Border', 'brando-addons') => '',
                             __('No Border', 'brando-addons') => 'no-border',
                             __('Top Border', 'brando-addons') => 'border-top',
                             __('Bottom Border', 'brando-addons') => 'border-bottom',
                             __('Left Border', 'brando-addons') => 'border-left',
                             __('Right Border', 'brando-addons') => 'border-right',
                            ),
            'dependency' => array( 'element' => 'desktop_show_border', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Border Color', 'brando-addons' ),
            'param_name' => 'column_border_color',
            'dependency' => array( 'element' => 'desktop_border_type', 'value' => array('border-top','border-bottom','border-left','border-right') ),
            'value' => '#e5e5e5',
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __( 'Border Size', 'brando-addons' ),
            'param_name' => 'column_border_size',
            'dependency' => array( 'element' => 'desktop_border_type', 'value' => array('border-top','border-bottom','border-left','border-right') ),
            'description' => __( 'Define border size like 2px', 'brando-addons' ),
            'value' => '1px',
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'column_border_type',
            'heading' => __( 'Border Type', 'brando-addons' ),
            'value' => array(__('no border', 'brando-addons') => '',
                             __('Dotted', 'brando-addons') => 'dotted',
                             __('Dashed', 'brando-addons') => 'dashed',
                             __('Solid', 'brando-addons') => 'solid',
                             __('Double', 'brando-addons') => 'double',
                            ),
            'std' => 'solid',
            'dependency' => array( 'element' => 'desktop_border_type', 'value' => array('border-top','border-bottom','border-left','border-right') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Border (For iPad/Tablet Device)', 'brando-addons'),
            'param_name' => 'ipad_border',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'border_setting', 'value' => array('1') ),
            'description' => __( 'Select Yes to hide border in iPad/Tablet Device.', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Border (For Mobile Device)', 'brando-addons'),
            'param_name' => 'mobile_border',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'border_setting', 'value' => array('1') ),
            'description' => __( 'Select Yes to hide border in Mobile Device.', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Required Padding Setting?', 'brando-addons'),
            'param_name' => 'padding_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_desktop_padding',
            'param_name' => 'desktop_padding',
            'heading' => __('Padding (For Desktop Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Padding (For Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_desktop_padding',
            'dependency' => array( 'element' => 'desktop_padding', 'value' => array('custom-desktop-padding') ),
            'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_mini_desktop_padding',
            'param_name' => 'desktop_mini_padding',
            'heading' => __('Padding (For Desktop Mini Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Padding (For Mini Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_mini_desktop_padding',
            'dependency' => array( 'element' => 'desktop_mini_padding', 'value' => array('custom-mini-desktop-padding') ),
            'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_ipad_padding',
            'param_name' => 'ipad_padding',
            'heading' => __('Padding (For iPad Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Padding (For iPad Device)', 'brando-addons' ),
            'param_name' => 'custom_ipad_padding',
            'dependency' => array( 'element' => 'ipad_padding', 'value' => array('custom-ipad-padding') ),
            'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_mobile_padding',
            'param_name' => 'mobile_padding',
            'heading' => __('Padding (For Mobile Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Padding (For Mobile Device)', 'brando-addons' ),
            'param_name' => 'custom_mobile_padding',
            'dependency' => array( 'element' => 'mobile_padding', 'value' => array('custom-mobile-padding') ),
            'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Required Margin Setting?', 'brando-addons'),
            'param_name' => 'margin_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_desktop_margin',
            'param_name' => 'desktop_margin',
            'heading' => __('Margin (For Desktop Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_desktop_margin',
            'dependency' => array( 'element' => 'desktop_margin', 'value' => array('custom-desktop-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_mini_desktop_margin',
            'param_name' => 'desktop_mini_margin',
            'heading' => __('Margin (For Desktop Mini Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For Mini Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_mini_desktop_margin',
            'dependency' => array( 'element' => 'desktop_mini_margin', 'value' => array('custom-mini-desktop-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_ipad_margin',
            'param_name' => 'ipad_margin',
            'heading' => __('Margin (For iPad Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For iPad Device)', 'brando-addons'),
            'param_name' => 'custom_ipad_margin',
            'dependency' => array( 'element' => 'ipad_margin', 'value' => array('custom-ipad-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_mobile_margin',
            'param_name' => 'mobile_margin',
            'heading' => __('Margin (For Mobile Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For Mobile Device)', 'brando-addons'),
            'param_name' => 'custom_mobile_margin',
            'dependency' => array( 'element' => 'mobile_margin', 'value' => array('custom-mobile-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Required Display Settings?', 'brando-addons'),
            'param_name' => 'display_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_display',
            'heading' => __('Display Setting (For Desktop Device)', 'brando-addons' ),
            'value' => array(__('Select Display Type', 'brando-addons') => '',
                             __('Block', 'brando-addons') => 'display-block',
                             __('Inline', 'brando-addons') => 'display-inline',
                             __('Inline Block', 'brando-addons') => 'display-inline-block',
                             __('None', 'brando-addons') => 'display-none',
                            ),
            'dependency' => array( 'element' => 'display_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'ipad_display',
            'heading' => __('Display Setting (For iPad/Tablet Device)', 'brando-addons' ),
            'value' => array(__('Select Display Type', 'brando-addons') => '',
                             __('Block', 'brando-addons') => 'sm-display-block',
                             __('Inline', 'brando-addons') => 'sm-display-inline',
                             __('Inline Block', 'brando-addons') => 'sm-display-inline-block',
                             __('None', 'brando-addons') => 'sm-display-none',
                            ),
            'dependency' => array( 'element' => 'display_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'mobile_display',
            'heading' => __('Display Setting (For Mobile Device)', 'brando-addons' ),
            'value' => array(__('Select Display Type', 'brando-addons') => '',
                             __('Block', 'brando-addons') => 'xs-display-block',
                             __('Inline', 'brando-addons') => 'xs-display-inline',
                             __('Inline Block', 'brando-addons') => 'xs-display-inline-block',
                             __('None', 'brando-addons') => 'xs-display-none',
                            ),
            'dependency' => array( 'element' => 'display_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
          array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Column with Clear both', 'brando-addons'),
            'param_name' => 'enable_clear_both',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'description' => __( 'Select Yes to mark as clear both', 'brando-addons' ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_clear_both',
            'heading' => __('Clear Both Setting (For Desktop Device)', 'brando-addons' ),
            'value' => array(__('Default', 'brando-addons') => '',
                             __('Clear Both', 'brando-addons') => 'clear-both',
                             __('Clear None', 'brando-addons') => 'clear-none',
                            ),
            'dependency' => array( 'element' => 'enable_clear_both', 'value' => array('1') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'desktop_mini_clear_both',
            'heading' => __('Clear Both Setting (For Desktop Mini Device)', 'brando-addons' ),
            'value' => array(__('Default', 'brando-addons') => '',
                             __('Clear Both', 'brando-addons') => 'md-clear-both',
                             __('Clear None', 'brando-addons') => 'md-clear-none',
                            ),
            'dependency' => array( 'element' => 'enable_clear_both', 'value' => array('1') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'ipad_clear_both',
            'heading' => __('Clear Both Setting (For iPad Device)', 'brando-addons' ),
            'value' => array(__('Default', 'brando-addons') => '',
                             __('Clear Both', 'brando-addons') => 'sm-clear-both',
                             __('Clear None', 'brando-addons') => 'sm-clear-none',
                            ),
            'dependency' => array( 'element' => 'enable_clear_both', 'value' => array('1') ),
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'mobile_clear_both',
            'heading' => __('Clear Both Setting (For Mobile Device)', 'brando-addons' ),
            'value' => array(__('Default', 'brando-addons') => '',
                             __('Clear Both', 'brando-addons') => 'xs-clear-both',
                             __('Clear None', 'brando-addons') => 'xs-clear-none',
                            ),
            'dependency' => array( 'element' => 'enable_clear_both', 'value' => array('1') ),
          ),
          array(
              'type' => 'brando_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => __('Pull Right', 'brando-addons'),
              'param_name' => 'pull_right',
              'value' => array(__('OFF', 'brando-addons') => '0', 
                               __('ON', 'brando-addons') => '1'
                              ),
          ),
          array(
              'type' => 'brando_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => __('Position Relative', 'brando-addons'),
              'param_name' => 'position_relative',
              'value' => array(__('OFF', 'brando-addons') => '0', 
                               __('ON', 'brando-addons') => '1'
                              ),
          ),
          array(
              'type' => 'brando_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => __('Overflow Hidden', 'brando-addons'),
              'param_name' => 'overflow_hidden',
              'value' => array(__('OFF', 'brando-addons') => '0', 
                               __('ON', 'brando-addons') => '1'
                              ),
          ),
           array(
            'type' => 'textfield',
            'param_name' => 'min_height',
            'heading' => __('Set Min Height', 'brando-addons' ),
            'value' => '',
            'description' => __( 'Define min height like 500px', 'brando-addons' ),
            'group' => 'Style',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __('SM Width', 'brando-addons' ),
            'param_name' => 'width',
            'value' => $brando_vc_column,
            'group' => 'Responsive Options',
            'description' => 'Select column width',
          ),
          array(
            'type' => 'column_offset',
            'heading' => __('Responsiveness', 'brando-addons' ),
            'param_name' => 'offset',
            'group' => 'Responsive Options',
            'description' => 'Adjust column for different screen sizes. Control width, offset and visibility settings.',
          ),
          array(
            'type' => 'dropdown',
            'param_name' => 'brando_column_animation_style',
            'heading' => __('Animation Style', 'brando-addons' ),
            'value' => brando_animation_style(),
            'group' => 'Animation',
          ),
          array(
            'type' => 'textfield',
            'heading' => __('Animation Duration', 'brando-addons' ),
            'param_name' => 'brando_column_animation_duration',
            'dependency' => array( 'element' => 'brando_column_animation_style', 'not_empty' => true ),
            'description' => __( 'Add duration like 300', 'brando-addons' ),
            'group' => 'Animation',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __('Image Thumbnail Size', 'brando-addons'),
            'param_name' => 'brando_image_srcset',
            'value' => brando_image_size(),
            'std' => 'full',
            'dependency' => array( 'element' => 'column_style', 'value' => array('image') ),
            'group' => 'Image',
          ),
          $brando_vc_extra_id,
          $brando_vc_extra_class,
      ),
  )
);

/*-----------------------------------------------------------------------------------*/
/* Vc_inner_column change End */
/*-----------------------------------------------------------------------------------*/