<?php
/**
 * Map For Blog Post Slider
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Blog Post Slider */
/*-----------------------------------------------------------------------------------*/

vc_map( array(
      'name' => __( 'Blog Post Slider', 'brando-addons' ),
      'base' => 'brando_post_slider',
      'category' => 'Brando',
      'icon' => 'fa fa-arrows-h brando-shortcode-icon',
      'description' => __( 'Create a post slider', 'brando-addons' ),
      'params' => array(
        array(
          'type' => 'dropdown',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Post Slider Style', 'brando-addons'),
          'param_name' => 'brando_post_slider_style',
          'value' => array(__('Select Post Slider Style', 'brando-addons') => '',
                           __('Post Slider Style1', 'brando-addons') => 'post-slider-1',
                           __('Post Slider Style2', 'brando-addons') => 'post-slider-2',
                          ),
        ),
        array(
          'type' => 'brando_preview_image',
          'heading' => __('Select pre-made style for block', 'brando-addons'),
          'param_name' => 'brando_post_slider_preview_image',
          'admin_label' => true,
          'value' => array(__('Select Post Slider Style', 'brando-addons') => '',
                           __('Post Slider Style1', 'brando-addons') => 'post-slider-1',
                           __('Post Slider Style2', 'brando-addons') => 'post-slider-2',
                          ),
        ),
        array(
          'type' => 'brando_multiple_select_option',
          'heading' => __('Categories', 'brando-addons'),
          'param_name' => 'brando_categories_list',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('No. of Post to Display', 'brando-addons'),
          'description' => __( 'Define value like 3', 'brando-addons' ),
          'param_name' => 'brando_post_per_page',
          'value' => '3',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Number', 'brando-addons'),
          'param_name' => 'brando_show_post_number',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post number', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Settings',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Number Color', 'brando-addons' ),
            'param_name' => 'brando_number_color',
            'dependency' => array( 'element' => 'brando_show_post_number', 'value' => array('1') ),
            'group' => 'Settings',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Title', 'brando-addons'),
          'param_name' => 'brando_show_post_title',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post title', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Settings',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Title Color', 'brando-addons' ),
            'param_name' => 'brando_title_color',
            'dependency' => array( 'element' => 'brando_show_post_title', 'value' => array('1') ),
            'group' => 'Settings',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Author', 'brando-addons'),
          'param_name' => 'brando_show_post_meta',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post meta', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Settings',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Author Color', 'brando-addons' ),
            'param_name' => 'brando_author_color',
            'dependency' => array( 'element' => 'brando_show_post_meta', 'value' => array('1') ),
            'group' => 'Settings',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Excerpt', 'brando-addons'),
          'param_name' => 'brando_show_excerpt',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select Yes to show excerpt, no to show full content', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Settings',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Excerpt Length', 'brando-addons' ),
          'description' => __( 'Enter numeric value like 20', 'brando-addons' ),
          'param_name'  => 'brando_excerpt_length',
          'value'     => '15',
          'dependency'  => array( 'element' => 'brando_show_excerpt', 'value' => array('1') ),
          'group' => 'Settings',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Show Post Date', 'brando-addons'),
          'param_name' => 'brando_show_post_date',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show post date', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Settings',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Date Color', 'brando-addons' ),
            'param_name' => 'brando_date_color',
            'dependency' => array( 'element' => 'brando_show_post_date', 'value' => array('1') ),
            'group' => 'Settings',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Date Format', 'brando-addons' ),
          'param_name'  => 'brando_date_format',
          'description' => wp_kses( 'Date format should be like mm/dd/yyyy, <a target="_blank" href="https://codex.wordpress.org/Formatting_Date_and_Time">click here</a> to see other date formates', 'brando-addons' ),
          'value'     => 'd m Y',
          'dependency'  => array( 'element' => 'brando_show_post_date', 'value' => array('1') ),
          'group' => 'Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('No. of Post to Display (For Desktop Device)', 'brando-addons'),
          'description' => __( 'Define value like 3', 'brando-addons' ),
          'param_name' => 'brando_post_per_page_desktop',
          'value' => '3',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('No. of Post to Display (For Mini Desktop Device)', 'brando-addons'),
          'description' => __( 'Define value like 3', 'brando-addons' ),
          'param_name' => 'brando_post_per_page_desktop_mini',
          'value' => '3',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('No. of Post to Display (For iPad/Tablet Device)', 'brando-addons'),
          'description' => __( 'Define value like 2', 'brando-addons' ),
          'param_name' => 'brando_post_per_page_ipad',
          'value' => '2',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('No. of Post to Display (For Mobile Device)', 'brando-addons'),
          'description' => __( 'Define value like 1', 'brando-addons' ),
          'param_name' => 'brando_post_per_page_mobile',
          'value' => '1',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Show Pagination', 'brando-addons'),
          'param_name' => 'show_pagination',
          'value' => array(__('OFF', 'brando-addons') => '0', 
                           __('ON', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select ON to show pagination in slider', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Pagination Style', 'brando-addons'),
          'param_name' => 'show_pagination_style',
          'admin_label' => true,
          'value' => array(__('Select Pagination Style', 'brando-addons') => '',
                           __('Dot Style', 'brando-addons') => '0',
                           __('Line Style', 'brando-addons') => '1',
                           __('Round Style', 'brando-addons') => '2',
                          ),
          'dependency' => array( 'element' => 'show_pagination', 'value' => array('1') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Pagination Color Style', 'brando-addons'),
          'param_name' => 'show_pagination_color_style',
          'admin_label' => true,
          'value' => array(__('Select Pagination Color Style', 'brando-addons') => '',
                           __('Dark Style', 'brando-addons') => '0',
                           __('Light Style', 'brando-addons') => '1',
                          ),
          'dependency' => array( 'element' => 'show_pagination', 'value' => array('1') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Show Navigation', 'brando-addons'),
          'param_name' => 'show_navigation',
          'value' => array(__('OFF', 'brando-addons') => '0', 
                           __('ON', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select ON to show navigation in slider', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Navigation Style', 'brando-addons'),
          'param_name' => 'show_navigation_style',
          'admin_label' => true,
          'value' => array(__('Select Navigation Style', 'brando-addons') => '',
                           __('Next/Prev Black Arrow', 'brando-addons') => '0',
                           __('Next/Prev White Arrow', 'brando-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'show_navigation', 'value' => array('1') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Cursor Color Style', 'brando-addons'),
          'param_name' => 'show_cursor_color_style',
          'admin_label' => true,
          'value' => array(__('Select Cursor Color Style', 'brando-addons') => '',
                           __('White Cursor', 'brando-addons') => 'white-cursor',
                           __('Black Cursor', 'brando-addons') => 'black-cursor',
                           __('Default Cursor', 'brando-addons') => 'no-cursor',
                          ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Autoplay', 'brando-addons'),
          'param_name' => 'autoplay',
          'value' => array(__('False', 'brando-addons') => '0', 
                           __('True', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select TRUE to autoplay slider', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Stop On Hover', 'brando-addons'),
          'param_name' => 'stoponhover',
          'value' => array(__('False', 'brando-addons') => '0', 
                           __('True', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select TRUE to stop autoplay when hover on slider', 'brando-addons' ),
          'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
          'group' => 'Slider Configuration',
        ), 
        array(
          'type' => 'dropdown',
          'heading' => __('Slide Delay Time', 'brando-addons'),
          'param_name' => 'slidespeed',
          'admin_label' => true,
          'value' => array(__('Select Slide Delay Time', 'brando-addons') => '',
                          __('500', 'brando-addons') => '500',
                           __('600', 'brando-addons') => '600',
                           __('700', 'brando-addons') => '700',
                           __('800', 'brando-addons') => '800',
                           __('900', 'brando-addons') => '900',
                           __('1000', 'brando-addons') => '1000',
                           __('2000', 'brando-addons') => '2000',
                           __('3000', 'brando-addons') => '3000',
                           __('4000', 'brando-addons') => '4000',
                           __('5000', 'brando-addons') => '5000',
                           __('6000', 'brando-addons') => '6000',
                           __('7000', 'brando-addons') => '7000',
                           __('8000', 'brando-addons') => '8000',
                           __('9000', 'brando-addons') => '9000',
                           __('10000', 'brando-addons') => '10000',
                        ),
          'description' => __('Select slide delay time (1ms = 100)', 'brando-addons'),
          'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
          'group' => 'Slider Configuration',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Display Items Order by', 'brando-addons' ),
          'param_name' => 'orderby',
          'value' => array(__('Select Order by', 'brando-addons') => '',
                           __( 'Date', 'brando-addons' ) => 'date',
                           __( 'ID', 'brando-addons' ) => 'ID',
                           __( 'Author', 'brando-addons' ) => 'author',
                           __( 'Title', 'brando-addons' ) => 'title',
                           __( 'Modified', 'brando-addons' ) => 'modified',
                           __( 'Random', 'brando-addons' ) => 'rand',
                           __( 'Comment count', 'brando-addons' ) => 'comment_count',
                           __( 'Menu order', 'brando-addons' ) => 'menu_order',
                          ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Order'
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Display Items Sort by', 'brando-addons' ),
          'param_name' => 'order',
          'value' => array(__('Select Sort by', 'brando-addons') => '',
                           __( 'Descending', 'brando-addons' ) => 'DESC',
                           __( 'Ascending', 'brando-addons' ) => 'ASC',
                          ),
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group' => 'Order'
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Slider ID', 'brando-addons' ),
          'param_name'  => 'brando_post_slider_id',
          'description' => 'Optional - Define element id (The id attribute specifies a unique id for an HTML element)',
          'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
          'group'       => 'Slider ID & Class'
        ),  
        array(
           'type'        => 'textfield',
           'heading'     => __('Slider Extra Class', 'brando-addons' ),
           'description' => 'Optional - add additional CSS class to this element, you can define multiple CSS class with use of space like "Class1 Class2"',
           'param_name'  => 'brando_post_slider_class',
           'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
           'group'       => 'Slider ID & Class'
        ),
        array(
            'type' => 'brando_custom_switch_option',
            'heading' => __('Show Separator', 'brando-addons'),
            'param_name' => 'brando_show_separator',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'description' => __( 'Select YES to show post separator', 'brando-addons' ),
            'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-2') ),
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Separator Color', 'brando-addons' ),
            'param_name' => 'brando_sep_color',
            'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
            'group' => 'Settings',
        ),
        array(
            'type' => 'textfield',
            'heading' => __('Separator Height', 'brando-addons' ),
            'param_name' => 'brando_seperator_height',
            'value'     => '2px',
            'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
            'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
            'group' => 'Settings',
        ),
        array(
            'type' => 'dropdown',
            'heading' => __('Image Thumbnail Size', 'brando-addons'),
            'param_name' => 'brando_image_srcset',
            'value' => brando_image_size(),
            'std' => 'full',
            'dependency'  => array( 'element' => 'brando_post_slider_style','value' => array('post-slider-1','post-slider-2') ),
            'group' => 'Image',
        ),
)));