<?php
/**
 * Map For Feature Box
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Feature Box */
/*-----------------------------------------------------------------------------------*/
$featurebox_class = 'brando_featurebox_'.time() . '-2-' . rand( 0, 100 );
vc_map( array(
  'name' => __('Features Box', 'brando-addons'),
  'description' => __('Place a features box', 'brando-addons'),
  'icon' => 'fa fa-building brando-shortcode-icon',
  'base' => 'brando_feature_box',
  'category' => 'Brando',
  'params' => array(
    array(
      'type' => 'dropdown',
      'heading' => __('Features Box Style', 'brando-addons'),
      'param_name' => 'brando_feature_type',
      'value' => array(__('Select Features Box Style', 'brando-addons') => '',
                       __('Feature Style 1', 'brando-addons')  => 'featurebox1',
                       __('Feature Style 2', 'brando-addons')  => 'featurebox2',
                       __('Feature Style 3', 'brando-addons')  => 'featurebox3',
                       __('Feature Style 4', 'brando-addons')  => 'featurebox4',
                       __('Feature Style 5', 'brando-addons')  => 'featurebox5',
                       __('Feature Style 6', 'brando-addons')  => 'featurebox6',
                       __('Feature Style 7', 'brando-addons')  => 'featurebox7',
                       __('Feature Style 8', 'brando-addons')  => 'featurebox8',
                       __('Feature Style 9', 'brando-addons')  => 'featurebox9',
                       __('Feature Style 10', 'brando-addons') => 'featurebox10',
                       __('Feature Style 11', 'brando-addons') => 'featurebox11',
                       __('Feature Style 12', 'brando-addons') => 'featurebox12',
                      ),
    ),
    array(
      'type' => 'brando_preview_image',
      'heading' => __('Select pre-made style for Feature', 'brando-addons'),
      'param_name' => 'feature_box_preview_image',
      'admin_label' => true,
      'value' => array(__('Select Feature Type', 'brando-addons') => '',
                       __('Feature Style 1', 'brando-addons') => 'featurebox1',
                       __('Feature Style 2', 'brando-addons') => 'featurebox2',
                       __('Feature Style 3', 'brando-addons') => 'featurebox3',
                       __('Feature Style 4', 'brando-addons') => 'featurebox4',
                       __('Feature Style 5', 'brando-addons') => 'featurebox5',
                       __('Feature Style 6', 'brando-addons') => 'featurebox6',
                       __('Feature Style 7', 'brando-addons') => 'featurebox7',
                       __('Feature Style 8', 'brando-addons') => 'featurebox8',
                       __('Feature Style 9', 'brando-addons') => 'featurebox9',
                       __('Feature Style 10', 'brando-addons') => 'featurebox10',
                       __('Feature Style 11', 'brando-addons') => 'featurebox11',
                       __('Feature Style 12', 'brando-addons') => 'featurebox12',
                      ),
      ),
    array(
      'type' => 'hidden',
      'heading' => __('Text', 'brando-addons' ),
      'param_name' => 'brando_token_class',
      'value' => $featurebox_class,
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'heading' => __('Custom Icon', 'brando-addons'),
      'param_name' => 'etline_custom_icon',
      'value' => array(__('NO', 'brando-addons') => '0',
                       __('YES', 'brando-addons') => '1'
                      ),
      'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2','featurebox3','featurebox7','featurebox9','featurebox5')),
    ),
    array(
      'type' => 'attach_image',
      'heading' => __('Custom Icon Image', 'brando-addons'),
      'param_name' => 'etline_custom_icon_image',
      'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '1' ),
      'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
    ),
    array(
          'type' => 'brando_etline_icon',
          'heading' => __('Select Et-Line Icon Type', 'brando-addons'),
          'param_name' => 'brando_et_line_icon_list',
          'admin_label' => true,
          'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '0' ),
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Number Text', 'brando-addons' ),
          'param_name' => 'brando_number',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1')),
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Price', 'brando-addons' ),
          'param_name' => 'brando_price',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6','featurebox8')),
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Title', 'brando-addons' ),
          'param_name' => 'brando_feature_title',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox3','featurebox4','featurebox5','featurebox6','featurebox7','featurebox8','featurebox9')),
     ),
    array(
          'type' => 'textfield',
          'heading' => __('Subtitle', 'brando-addons' ),
          'param_name' => 'brando_feature_subtitle',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox8')),
    ),
    array(
          'type' => 'attach_image',
          'heading' => __('Image', 'brando-addons' ),
          'param_name' => 'brando_feature_image',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox4','featurebox8')),
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Show Border', 'brando-addons'),
          'param_name' => 'brando_show_border',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'description' => __( 'Select YES to show border in icon', 'brando-addons' ),
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox11')),
    ),
    array(
      'type'        => 'vc_link',
      'heading'     => __('Button Config', 'brando-addons' ),
      'param_name'  => 'brando_button_text',
      'admin_label' => true,
      'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6') ),
    ),
    array(
          'type' => 'textarea_html',
          'heading' => __('Description', 'brando-addons'),
          'param_name' => 'content',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox4','featurebox5','featurebox6','featurebox7','featurebox9')),    
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Box With Gray Border', 'brando-addons'),
      'param_name' => 'with_gray_border',
      'value' => array(__('No', 'brando-addons')  => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2') ),
    ),
    array(
          'type' => 'brando_posts_list',
          'heading' => __('Blog Post', 'brando-addons'),
          'param_name' => 'brando_posts_list',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10','featurebox11','featurebox12')),
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Image Position', 'brando-addons'),
          'param_name' => 'brando_image_pos',
          'value' => array(__('Left', 'brando-addons')  => '0', 
                           __('Right', 'brando-addons') => '1',
                          ),
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox12')),
    ),
    array(
      'type'        => 'textfield',
      'heading'     => __('Link (full url with http)', 'brando-addons' ),
      'param_name'  => 'brando_link',
      'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox3','featurebox5','featurebox7','featurebox8','featurebox9')),
    ),
    array(
      'type'        => 'dropdown',
      'heading'     => __('Link Target', 'brando-addons' ),
      'param_name'  => 'brando_link_target',
      'value' => array(__('Self', 'brando-addons') => '_self', 
                       __('New tab / window', 'brando-addons') => '_blank'
                      ),
      'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox3','featurebox5','featurebox7','featurebox8','featurebox9')),
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Enable Separator', 'brando-addons'),
          'param_name' => 'brando_enable_seperator',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'std' => '1',
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox5','featurebox9','featurebox10','featurebox12')),
    ),    
    array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => __( 'Separator Color', 'brando-addons' ),
        'param_name' => 'brando_sep_color',
        'dependency' => array( 'element' => 'brando_enable_seperator', 'value' => array('1') ),
      ),
      array(
        'type' => 'textfield',
        'heading' => __('Separator Height', 'brando-addons' ),
        'param_name' => 'brando_seperator_height',
        'value'     => '2px',
        'dependency' => array( 'element' => 'brando_enable_seperator', 'value' => array('1') ),
        'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
      ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Enable Icon', 'brando-addons'),
          'param_name' => 'brando_feature_icon',
          'value' => array(__('NO', 'brando-addons') => '0', 
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_feature_type', 'value' => array('featurebox4')),
    ),
    
    array(
          'type' => 'dropdown',
          'heading' => __('Select Icon Size', 'brando-addons'),
          'param_name' => 'counter_icon_size',
          'admin_label' => true,
          'value' => array(__('Default', 'brando-addons') => '',
                           __('Extra Large', 'brando-addons') => 'icon-extra-large', 
                           __('Large', 'brando-addons') => 'icon-large',
                           __('Medium', 'brando-addons') => 'icon-medium',
                           __('Small', 'brando-addons') => 'icon-small',
                           __('Extra Small', 'brando-addons') => 'icon-extra-small',
                          ),
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2','featurebox4','featurebox5','featurebox3','featurebox7','featurebox9') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'dropdown',
          'heading' => __('Select Border transperent', 'brando-addons'),
          'param_name' => 'brando_border_transperent',
          'admin_label' => true,
          'value' => array(__('Select Border-transperent', 'brando-addons') => '',
                           __('White', 'brando-addons') => 'border-transperent-white',
                           __('Black', 'brando-addons') => 'border-transperent-black-light', 
                           __('Custom Color', 'brando-addons') => 'custom',
                           ),
          'dependency' => array( 'element' => 'brando_show_border', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => esc_html__( ' Color', 'brando-addons' ),
          'param_name' => 'brando_border_color',
          'dependency' => array( 'element' => 'brando_border_transperent', 'value' => array('custom') ),
          'description' => esc_html__( 'Border Custom color',   'brando-addons' ),
          'group' => 'Style',
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Icon Color', 'brando-addons' ),
          'param_name' => 'brando_icon_color',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2','featurebox4','featurebox5','featurebox3','featurebox7','featurebox9') ),
          'group' => 'Style',
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'title_settings',
          'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox3','featurebox4','featurebox5','featurebox6','featurebox7','featurebox8','featurebox9','featurebox10','featurebox11','featurebox12') ),
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'subtitle_settings',
          'heading'     => esc_html__( 'Font Settings For Subtitle', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox8') ),
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'postmeta_settings',
          'heading'     => esc_html__( 'Font Settings For Post Meta', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10','featurebox11','featurebox12') ),
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'number_settings',
          'heading'     => esc_html__( 'Font Settings For Number', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1') ),
          'hide_font_settings_element_lg' => array('text-align','font-transform'),
          'hide_font_settings_element_md' => array('text-align','font-transform'),
          'hide_font_settings_element_sm' => array('text-align','font-transform'),
          'hide_font_settings_element_xs' => array('text-align','font-transform'),
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'price_settings',
          'heading'     => esc_html__( 'Font Settings For Price', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6','featurebox8') ),
          'hide_font_settings_element_lg' => array('text-align','font-transform'),
          'hide_font_settings_element_md' => array('text-align','font-transform'),
          'hide_font_settings_element_sm' => array('text-align','font-transform'),
          'hide_font_settings_element_xs' => array('text-align','font-transform'),
    ),
    array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'category_settings',
          'heading'     => esc_html__( 'Font Settings For category', 'hcode-addons' ),
          'group' => 'Font Settings',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10') ),
    ),
    array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Post Title', 'brando-addons'),
        'param_name' => 'brando_show_post_title',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select Yes to show post title', 'brando-addons' ),
        'std' => '1',
        'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10','featurebox11','featurebox12') ),
        'group' => 'Configuration',
    ),
    array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Excerpt', 'brando-addons'),
        'param_name' => 'brando_show_excerpt',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select Yes to show excerpt, no to show full content', 'brando-addons' ),
        'std'         => '1',
        'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10') ),
        'group' => 'Configuration',
    ),
    array(
        'type'        => 'textfield',
        'heading'     => __('Excerpt Length', 'brando-addons' ),
        'description' => __( 'Enter numeric value like 20', 'brando-addons' ),
        'param_name'  => 'brando_excerpt_length',
        'value'     => '15',
        'dependency'  => array( 'element' => 'brando_show_excerpt', 'value' => array('1') ),
        'group' => 'Configuration',
    ),
    array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Post Author', 'brando-addons'),
        'param_name' => 'brando_show_post_author',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select Yes to show post date', 'brando-addons' ),
        'std' => '1',
        'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10','featurebox11') ),
        'group' => 'Configuration',
    ),
    array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Post Category', 'brando-addons'),
        'param_name' => 'brando_show_post_category',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select Yes to show post category', 'brando-addons' ),
        'std' => '1',
        'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10') ),
        'group' => 'Configuration',
    ),
    array(
        'type' => 'brando_custom_switch_option',
        'heading' => __('Show Post Date', 'brando-addons'),
        'param_name' => 'brando_show_post_date',
        'value' => array(__('No', 'brando-addons') => '0', 
                         __('Yes', 'brando-addons') => '1'
                        ),
        'description' => __( 'Select Yes to show post date', 'brando-addons' ),
        'std' => '1',
        'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10','featurebox11','featurebox12') ),
        'group' => 'Configuration',
    ),
    array(
        'type'        => 'textfield',
        'heading'     => __('Date Format', 'brando-addons' ),
        'param_name'  => 'brando_date_format',
        'description' => wp_kses( 'Date format should be like mm/dd/yyyy, <a target="_blank" href="https://codex.wordpress.org/Formatting_Date_and_Time">click here</a> to see other date formates', 'brando-addons' ),
        'value'     => 'd m Y',
        'dependency'  => array( 'element' => 'brando_show_post_date', 'value' => array('1') ),
        'group' => 'Configuration',
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Title Color', 'brando-addons' ),
          'param_name' => 'brando_title_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2','featurebox3','featurebox4','featurebox5','featurebox6','featurebox7','featurebox8','featurebox9','featurebox10','featurebox11','featurebox12') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Hover Title Color', 'brando-addons' ),
          'param_name' => 'brando_hover_title_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Subtitle Color', 'brando-addons' ),
          'param_name' => 'brando_subtitle_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox8') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Number Color', 'brando-addons' ),
          'param_name' => 'brando_number_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Hover Border Color', 'brando-addons' ),
          'param_name' => 'brando_hover_border_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Hover BG Color', 'brando-addons' ),
          'param_name' => 'brando_hover_bg_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox2') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Post Meta Color', 'brando-addons' ),
          'param_name' => 'brando_meta_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox10') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Price Color', 'brando-addons' ),
          'param_name' => 'brando_price_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6','featurebox8') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Price BG Color', 'brando-addons' ),
          'param_name' => 'brando_price_bg_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6','featurebox8') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Title BG Color', 'brando-addons' ),
          'param_name' => 'brando_title_bg_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox6') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Feature Author Color', 'brando-addons' ),
          'param_name' => 'brando_author_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox11') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Post Date Color', 'brando-addons' ),
          'param_name' => 'brando_post_date_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox11','featurebox12') ),
    ),
    array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Icon Color', 'brando-addons' ),
          'param_name' => 'brando_post_icon_color',
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox11') ),
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Required Padding Setting?', 'brando-addons'),
          'param_name' => 'padding_setting',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2') ),
    ),
    array(
          'type' => 'brando_custom_desktop_padding',
          'param_name' => 'desktop_padding',
          'heading' => __('Padding (For Desktop Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Custom Padding (For Desktop Device)', 'brando-addons' ),
          'param_name' => 'custom_desktop_padding',
          'dependency' => array( 'element' => 'desktop_padding', 'value' => array('custom-desktop-padding') ),
          'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
    ),
    array(
          'type' => 'brando_custom_ipad_padding',
          'param_name' => 'ipad_padding',
          'heading' => __('Padding (For iPad Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Padding (For iPad Device)', 'brando-addons' ),
      'param_name' => 'custom_ipad_padding',
      'dependency' => array( 'element' => 'ipad_padding', 'value' => array('custom-ipad-padding') ),
      'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Style',
    ),
    array(
          'type' => 'brando_custom_mobile_padding',
          'param_name' => 'mobile_padding',
          'heading' => __('Padding (For Mobile Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Custom Padding (For Mobile Device)', 'brando-addons' ),
      'param_name' => 'custom_mobile_padding',
      'dependency' => array( 'element' => 'mobile_padding', 'value' => array('custom-mobile-padding') ),
      'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
      'group' => 'Style',
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Required Margin Setting?', 'brando-addons'),
          'param_name' => 'margin_setting',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'group' => 'Style',
          'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox2') ),
    ),
    array(
          'type' => 'brando_custom_desktop_margin',
          'param_name' => 'desktop_margin',
          'heading' => __('Margin (For Desktop Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Custom Margin (For Desktop Device)', 'brando-addons' ),
          'param_name' => 'custom_desktop_margin',
          'dependency' => array( 'element' => 'desktop_margin', 'value' => array('custom-desktop-margin') ),
          'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons'),
          'group' => 'Style',
    ),
    array(
          'type' => 'brando_custom_ipad_margin',
          'param_name' => 'ipad_margin',
          'heading' => __('Margin (For iPad Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Custom Margin (For iPad Device)', 'brando-addons'),
          'param_name' => 'custom_ipad_margin',
          'dependency' => array( 'element' => 'ipad_margin', 'value' => array('custom-ipad-margin') ),
          'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
    ),
    array(
          'type' => 'brando_custom_mobile_margin',
          'param_name' => 'mobile_margin',
          'heading' => __('Margin (For Mobile Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
    ),
    array(
          'type' => 'textfield',
          'heading' => __('Custom Margin (For Mobile Device)', 'brando-addons'),
          'param_name' => 'custom_mobile_margin',
          'dependency' => array( 'element' => 'mobile_margin', 'value' => array('custom-mobile-margin') ),
          'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Image Thumbnail Size', 'brando-addons'),
      'param_name' => 'brando_image_srcset',
      'value' => brando_image_size(),
      'std' => 'full',
      'dependency' => array( 'element' => 'brando_feature_type', 'value' => array('featurebox1','featurebox8','featurebox10','featurebox12') ),
      'group' => 'Image',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Custom Image Size', 'brando-addons'),
      'param_name' => 'brando_custom_image_srcset',
      'value' => brando_image_size(),
      'std' => 'full',
      'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '1' ),
      'group' => 'Image',
    ),
    $brando_vc_extra_id,
    $brando_vc_extra_class, 
    )
) );