<?php
/**
 * Shortcode For Testimonial
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Testimonial */
/*-----------------------------------------------------------------------------------*/

$testimonial_class = 'brando_testimonial_'.time() . '-2-' . rand( 0, 100 );
$testimonial_padding_class = 'brando_testimonial_'.time() . '-2-' . rand( 0, 100 );
vc_map( array(
      'name' => __( 'Testimonial', 'brando-addons' ),
      'base' => 'brando_testimonial',
      'category' => 'Brando',
      'icon' => 'fa fa-list-alt brando-shortcode-icon',
      'description' => __( 'Create a testimonial', 'brando-addons' ),
      'params' => array(
        array(
          'type' => 'hidden',
          'heading' => __('Text', 'brando-addons' ),
          'param_name' => 'brando_token_class',
          'value' => $testimonial_class,
        ),
        array(
          'type' => 'hidden',
          'heading' => __('Text', 'brando-addons' ),
          'param_name' => 'brando_padding_token_class',
          'value' => $testimonial_padding_class,
        ),
        array(
          'type' => 'dropdown',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Testimonial Style', 'brando-addons'),
          'param_name' => 'brando_testimonial_premade_style',
          'value' => array(__('Select Testimonial Style', 'brando-addons') => '',
                           __('Testimonial Style1', 'brando-addons') => 'testimonial-1',
                           __('Testimonial Style2', 'brando-addons') => 'testimonial-2',
                           __('Testimonial Style3', 'brando-addons') => 'testimonial-3',
                           __('Testimonial Style4', 'brando-addons') => 'testimonial-4',
                          ),
        ),
        array(
          'type' => 'brando_preview_image',
          'heading' => __('Select pre-made style for testimonial', 'brando-addons'),
          'param_name' => 'brando_testimonial_preview_image',
          'admin_label' => true,
          'value' => array(__('Select Testimonial Style', 'brando-addons') => '',
                           __('Testimonial Style1', 'brando-addons') => 'testimonial-1',
                           __('Testimonial Style2', 'brando-addons') => 'testimonial-2',
                           __('Testimonial Style3', 'brando-addons') => 'testimonial-3',
                           __('Testimonial Style4', 'brando-addons') => 'testimonial-4',
                          ),
        ),
        array(
            'type' => 'attach_image',
            'heading' => __( 'Image', 'brando-addons' ),
            'param_name' => 'brando_image',
            'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-2','testimonial-3') ),
        ),
        array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Show Quote Icon?', 'brando-addons'),
            'param_name' => 'brando_show_quote_icon',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'std' => '1',
            'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3','testimonial-4') ),
          ),
        array(
          'type' => 'textfield',
          'heading' => __('Testimonial Quote Icon', 'brando-addons'),
          'param_name' => 'brando_testimonial_quotes',
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-2') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Testimonial Title', 'brando-addons'),
          'param_name' => 'brando_testimonial_title',
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3','testimonial-4') ),
        ),
        array(
          'type' => 'textarea_html',
          'heading' => __('Content', 'brando-addons'),
          'param_name' => 'content',
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3','testimonial-4') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Author Name', 'brando-addons'),
          'param_name' => 'brando_author_name',
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Author Designation', 'brando-addons'),
          'param_name' => 'brando_author_des',
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2') ),
        ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Author Name Color', 'brando-addons' ),
          'param_name' => 'author_name_color',
          'description' => __( 'Choose Author Name Color', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Author Designation Color', 'brando-addons' ),
          'param_name' => 'author_designation_color',
          'description' => __( 'Choose Author Designation Color', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Testimonial Title Color', 'brando-addons' ),
          'param_name' => 'testimonial_title_color',
          'description' => __( 'Choose Testimonial Title Color', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3','testimonial-4') ),
          'group' => 'Color',
      ),
      array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Testimonial Quote Icon Color', 'brando-addons' ),
          'param_name' => 'testimonial_icon_color',
          'description' => __( 'Choose Testimonial Quote Icon Color', 'brando-addons' ),
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3','testimonial-4') ),
          'group' => 'Color',
      ),
      array(
          'type'        => 'textfield',
          'heading'     => __('Facebook Url', 'brando-addons' ),
          'param_name'  => 'brando_facebook_url',
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3') ),
          'group' => 'Social',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Twitter Url', 'brando-addons' ),
          'param_name'  => 'brando_twitter_url',
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3') ),
          'group' => 'Social',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Google Plus Url', 'brando-addons' ),
          'param_name'  => 'brando_gplus_url',
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3') ),
          'group' => 'Social',
        ),
        array(
          'type'        => 'textfield',
          'heading'     => __('Dribble Url', 'brando-addons' ),
          'param_name'  => 'brando_dribble_url',
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3') ),
          'group' => 'Social',
        ),
        array(
          'type' => 'textarea_raw_html',
          'heading' => __( 'Custom Icon & Link Code', 'brando-addons' ),
          'param_name' => 'brando_testimonial_custom_link',
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3') ),
          'group' => 'Social',
        ),
        array(
          'type'        => 'vc_link',
          'heading'     => __('Button Configuration', 'brando-addons' ),
          'param_name'  => 'button_config',
          'admin_label' => true,
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-4') ),
        ),
        array(
            'type' => 'brando_custom_switch_option',
            'holder' => 'div',
            'class' => '',
            'heading' => __('Required Padding Setting?', 'brando-addons'),
            'param_name' => 'padding_setting',
            'value' => array(__('No', 'brando-addons') => '0', 
                             __('Yes', 'brando-addons') => '1'
                            ),
            'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3','testimonial-4') ),
            'group' => 'Style',
          ),
        array(
          'type' => 'brando_custom_desktop_padding',
          'param_name' => 'desktop_padding',
          'heading' => __('Padding (For Desktop Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
          'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Custom Padding (For Desktop Device)', 'brando-addons' ),
          'param_name' => 'custom_desktop_padding',
          'dependency' => array( 'element' => 'desktop_padding', 'value' => array('custom-desktop-padding') ),
          'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),

            'group' => 'Style',
        ),
        array(
            'type' => 'brando_custom_mini_desktop_padding',
            'param_name' => 'desktop_mini_padding',
            'heading' => __('Padding (For Desktop Mini Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
        array(
            'type' => 'textfield',
            'heading' => __('Custom Padding (For Mini Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_mini_desktop_padding',
            'dependency' => array( 'element' => 'desktop_mini_padding', 'value' => array('custom-mini-desktop-padding') ),
            'description' => __( 'Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
        array(
          'type' => 'brando_custom_ipad_padding',
          'param_name' => 'ipad_padding',
          'heading' => __('Padding (For iPad Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Custom Padding (For iPad Device)', 'brando-addons' ),
          'param_name' => 'custom_ipad_padding',
          'dependency' => array( 'element' => 'ipad_padding', 'value' => array('custom-ipad-padding') ),
          'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
        ),
        array(
          'type' => 'brando_custom_mobile_padding',
          'param_name' => 'mobile_padding',
          'heading' => __('Padding (For Mobile Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'padding_setting', 'value' => array('1') ),
            'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Custom Padding (For Mobile Device)', 'brando-addons' ),
          'param_name' => 'custom_mobile_padding',
          'dependency' => array( 'element' => 'mobile_padding', 'value' => array('custom-mobile-padding') ),
          'description' => __('Specify padding like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
        ),
        array(
          'type' => 'brando_custom_switch_option',
          'holder' => 'div',
          'class' => '',
          'heading' => __('Required Margin Setting?', 'brando-addons'),
          'param_name' => 'margin_setting',
          'value' => array(__('No', 'brando-addons') => '0', 
                           __('Yes', 'brando-addons') => '1'
                          ),
          'dependency'  => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-1','testimonial-2','testimonial-3','testimonial-4') ),
          'group' => 'Style',
        ),
        array(
          'type' => 'brando_custom_desktop_margin',
          'param_name' => 'desktop_margin',
          'heading' => __('Margin (For Desktop Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Custom Margin (For Desktop Device)', 'brando-addons' ),
          'param_name' => 'custom_desktop_margin',
          'dependency' => array( 'element' => 'desktop_margin', 'value' => array('custom-desktop-margin') ),
          'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
        ),
        array(
            'type' => 'brando_custom_mini_desktop_margin',
            'param_name' => 'desktop_mini_margin',
            'heading' => __('Margin (For Desktop Mini Device)', 'brando-addons' ),
            'value' => '',
            'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
          ),
        array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For Mini Desktop Device)', 'brando-addons' ),
            'param_name' => 'custom_mini_desktop_margin',
            'dependency' => array( 'element' => 'desktop_mini_margin', 'value' => array('custom-mini-desktop-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
        array(
          'type' => 'brando_custom_ipad_margin',
          'param_name' => 'ipad_margin',
          'heading' => __('Margin (For iPad Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'textfield',
            'heading' => __('Custom Margin (For iPad Device)', 'brando-addons'),
            'param_name' => 'custom_ipad_margin',
            'dependency' => array( 'element' => 'ipad_margin', 'value' => array('custom-ipad-margin') ),
            'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
            'group' => 'Style',
          ),
        array(
          'type' => 'brando_custom_mobile_margin',
          'param_name' => 'mobile_margin',
          'heading' => __('Margin (For Mobile Device)', 'brando-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'margin_setting', 'value' => array('1') ),
          'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Custom Margin (For Mobile Device)', 'brando-addons'),
          'param_name' => 'custom_mobile_margin',
          'dependency' => array( 'element' => 'mobile_margin', 'value' => array('custom-mobile-margin') ),
          'description' => __( 'Specify margin like (10px 12px 10px 12px or 10px or 10%...)', 'brando-addons' ),
          'group' => 'Style',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'title_settings',
          'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
          'dependency' => array( 'element' => 'brando_testimonial_premade_style', 'value' => array('testimonial-3','testimonial-4') ),
          'group' => 'Font Settings',
        ),
        $brando_vc_extra_id,
        $brando_vc_extra_class, 
)));