<?php
/**
 * Map For Icon
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Icons */
/*-----------------------------------------------------------------------------------*/
vc_map( array(
  'name' => __('Font Icons', 'brando-addons'),
  'base' => 'brando_font_icons',
  'category' => 'Brando',
  'content_element' => true,
  'description' => __( 'Add font awesome/et-line icons', 'brando-addons' ),
  'icon' => 'fa fa-flag brando-shortcode-icon', //URL or CSS class with icon image.
  'params' => array(
    array(
      'type' => 'dropdown',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Font Icon Type', 'brando-addons'),
      'param_name' => 'brando_font_icon_type',
      'value' => array(__('Select Font Icon Type', 'brando-addons') => '',
                       __('Font Awesome Icons', 'brando-addons') => 'brando_font_awesome_icons',
                       __('Et-line Icons', 'brando-addons') => 'brando_et_line_icons',
                      ),
    ),
    array(
      'type' => 'dropdown',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Font Awesome Style', 'brando-addons'),
      'param_name' => 'brando_font_icon_premade_style',
      'value' => array(__('Select Font Awesome style', 'brando-addons') => '',
                       __('Font Style1', 'brando-addons') => 'font-awesome-icons-1',
                      ),
      'dependency'  => array( 'element' => 'brando_font_icon_type', 'value' => array('brando_font_awesome_icons')),
    ),
    array(
      'type' => 'brando_preview_image',
      'heading' => __('Select pre-made style for tab', 'brando-addons'),
      'param_name' => 'brando_font_icon_preview_image',
      'admin_label' => true,
      'value' => array(__('Font image', 'brando-addons') => '',
                       __('Font image1', 'brando-addons') => 'font-awesome-icons-1',
                      ),
      'dependency'  => array( 'element' => 'brando_font_icon_type', 'value' => array('brando_font_awesome_icons')),
    ),
    array(
      'type' => 'dropdown',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Et-Line Style', 'brando-addons'),
      'param_name' => 'brando_et_icon_premade_style',
      'value' => array(__('Select Et-Line Style', 'brando-addons') => '',
                       __('Font Style1', 'brando-addons') => 'et-line-icons-1',
                       __('Font Style2', 'brando-addons') => 'et-line-icons-2',
                       __('Font Style3', 'brando-addons') => 'et-line-icons-3',
                       __('Font Style4', 'brando-addons') => 'et-line-icons-4',
                       __('Font Style5', 'brando-addons') => 'et-line-icons-5',
                       __('Font Style6', 'brando-addons') => 'et-line-icons-6',
                       __('Font Style7', 'brando-addons') => 'et-line-icons-7',
                       __('Font Style8', 'brando-addons') => 'et-line-icons-8',
                       __('Font Style9', 'brando-addons') => 'et-line-icons-9',
                       __('Font Style10', 'brando-addons') => 'et-line-icons-10',
                       __('Font Style11', 'brando-addons') => 'et-line-icons-11',
                       __('Font Style12', 'brando-addons') => 'et-line-icons-12',
                    ),
      'dependency'  => array( 'element' => 'brando_font_icon_type', 'value' => array('brando_et_line_icons')),
    ),
    array(
      'type' => 'brando_preview_image',
      'heading' => __('Select pre-made style for tab', 'brando-addons'),
      'param_name' => 'brando_et_icon_preview_image',
      'admin_label' => true,
      'value' => array(__('Font image', 'brando-addons') => '',
                       __('Font image1', 'brando-addons') => 'et-line-icons-1',
                       __('Font image2', 'brando-addons') => 'et-line-icons-2',
                       __('Font image3', 'brando-addons') => 'et-line-icons-3',
                       __('Font image4', 'brando-addons') => 'et-line-icons-4',
                       __('Font image5', 'brando-addons') => 'et-line-icons-5',
                       __('Font image6', 'brando-addons') => 'et-line-icons-6',
                       __('Font image7', 'brando-addons') => 'et-line-icons-7',
                       __('Font image8', 'brando-addons') => 'et-line-icons-8',
                       __('Font image9', 'brando-addons') => 'et-line-icons-9',
                       __('Font image10', 'brando-addons') => 'et-line-icons-10',
                       __('Font image11', 'brando-addons') => 'et-line-icons-11',
                       __('Font image12', 'brando-addons') => 'et-line-icons-12',
                      ),
      'dependency'  => array( 'element' => 'brando_font_icon_type', 'value' => array('brando_et_line_icons')),
    ),
    array(
          'type' => 'brando_custom_switch_option',
          'heading' => __('Custom Icon', 'brando-addons'),
          'param_name' => 'font_awesome_custom_icon',
          'value' => array(__('NO', 'brando-addons') => '0',
                           __('YES', 'brando-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'brando_font_icon_premade_style', 'not_empty' => true),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Icon Image', 'brando-addons'),
          'param_name' => 'font_awesome_custom_icon_image',
          'dependency' => array( 'element' => 'font_awesome_custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
        ),
    array(
      'type' => 'brando_fontawesome_icon',
      'heading' => __('Font Awesome Icon Type', 'brando-addons'),
      'param_name' => 'brando_font_awesome_icon_list',
      'admin_label' => true,
      'dependency' => array( 'element' => 'font_awesome_custom_icon', 'value' => '0' ),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'heading' => __('Custom Icon', 'brando-addons'),
      'param_name' => 'etline_custom_icon',
      'value' => array(__('NO', 'brando-addons') => '0',
                       __('YES', 'brando-addons') => '1'
                      ),
      'dependency' => array( 'element' => 'brando_et_icon_premade_style', 'not_empty' => true),
    ),
    array(
      'type' => 'attach_image',
      'heading' => __('Custom Icon Image', 'brando-addons'),
      'param_name' => 'etline_custom_icon_image',
      'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '1' ),
      'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
    ),
    array(
      'type' => 'brando_etline_icon',
      'heading' => __('Et-Line Icon Type', 'brando-addons'),
      'param_name' => 'brando_et_line_icon_list',
      'admin_label' => true,
      'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '0' ),
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Icon Size', 'brando-addons'),
      'param_name' => 'brando_font_icon_size',
      'admin_label' => true,
      'value' => array(__('Select Icon Size', 'brando-addons') => '',
                       __('Extra Large', 'brando-addons') => 'icon-extra-large', 
                       __('Large', 'brando-addons') => 'icon-large',
                       __('Medium', 'brando-addons') => 'icon-medium',
                       __('Small', 'brando-addons') => 'icon-small',
                       __('Extra Small', 'brando-addons') => 'icon-extra-small',
                      ),
      'dependency' => array( 'element' => 'brando_font_icon_premade_style', 'value' => array('font-awesome-icons-1')),
    ),

    // For Et line icons
    array(
      'type' => 'dropdown',
      'heading' => __('Icon Box Size', 'brando-addons'),
      'param_name' => 'brando_et_icon_box_size',
      'admin_label' => true,
      'value' => array(__('Select Icon Box Size', 'brando-addons') => '',
                       __('Large', 'brando-addons') => 'i-large-box',
                       __('Medium', 'brando-addons') => 'i-medium-box',
                       __('Small', 'brando-addons') => 'i-small-box',
                       __('Extra Small', 'brando-addons') => 'i-extra-small-box',
                      ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'not_empty' => true),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Show Border', 'brando-addons'),
      'param_name' => 'et_show_border',
      'value' => array(__('No', 'brando-addons') => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'description' => __( 'Select YES to show border in icon', 'brando-addons' ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-2','et-line-icons-4','et-line-icons-8','et-line-icons-10')),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Show Rounded Border', 'brando-addons'),
      'param_name' => 'show_et_border_rounded',
      'value' => array(__('No', 'brando-addons') => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'description' => __( 'Select YES to show rounded border in icon', 'brando-addons' ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-2','et-line-icons-3','et-line-icons-4','et-line-icons-5','et-line-icons-6','et-line-icons-8','et-line-icons-9','et-line-icons-10','et-line-icons-11','et-line-icons-12')),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Show Plain Icons', 'brando-addons'),
      'param_name' => 'et_plain',
      'value' => array(__('No', 'brando-addons') => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'description' => __( 'Select YES to show plain icon', 'brando-addons' ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-1','et-line-icons-7')),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Show Circled Icon', 'brando-addons'),
      'param_name' => 'circled',
      'value' => array(__('No', 'brando-addons')  => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'description' => __( 'Select YES to show circled icon', 'brando-addons' ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-7','et-line-icons-8','et-line-icons-9','et-line-icons-10','et-line-icons-11','et-line-icons-12')),
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Icon Box Decoration', 'brando-addons'),
      'param_name' => 'brando_et_icon_box_decoration',
      'admin_label' => true,
      'value' => array(__('Select Icon Box Decoration', 'brando-addons') => '',
                       __('Light', 'brando-addons') => 'i-light', 
                       __('3d', 'brando-addons') => 'i-3d',
                       __('3d Border', 'brando-addons') => 'i-3d-border',
                      ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-4','et-line-icons-5','et-line-icons-6','et-line-icons-10','et-line-icons-11','et-line-icons-12')),
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Icon Box Background Color', 'brando-addons'),
      'param_name' => 'brando_et_icon_box_background_color',
      'admin_label' => true,
      'value' => array(__('Select Icon Box Background Color', 'brando-addons') => '',
                       __('Orange', 'brando-addons') => 'bg-orange', 
                       __('Yellow', 'brando-addons') => 'bg-yellow',
                       __('Yellow Ochre', 'brando-addons') => 'bg-yellow-ochre',
                       __('Green', 'brando-addons') => 'bg-green',
                       __('Dark Blue', 'brando-addons') => 'bg-dark-blue',
                       __('Dark Gray', 'brando-addons') => 'bg-dark-gray',
                      ),
      'dependency'  => array( 'element' => 'brando_et_icon_premade_style', 'value' => array('et-line-icons-6','et-line-icons-12')),
    ),
    array(
        'type' => 'dropdown',
        'heading' => __('Custom Image Size', 'brando-addons'),
        'param_name' => 'brando_custom_image_srcset',
        'value' => brando_image_size(),
        'std' => 'full',
        'dependency' => array( 'element' => 'font_awesome_custom_icon', 'value' => '1' ),
        'group' => 'Image',
    ),
    array(
        'type' => 'dropdown',
        'heading' => __('Custom Image Size', 'brando-addons'),
        'param_name' => 'brando_custom_etline_image_srcset',
        'value' => brando_image_size(),
        'std' => 'full',
        'dependency' => array( 'element' => 'etline_custom_icon', 'value' => '1' ),
        'group' => 'Image',
    ),
    $brando_vc_extra_id,
    $brando_vc_extra_class,
  ),
) );