<?php
/**
 * Map For Counter 
 *
 * @package Brando
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Brando Counter  */
/*-----------------------------------------------------------------------------------*/
vc_map( 
  array(
  'name' => __('Counter', 'brando-addons'),
  'base' => 'brando_counter_or_skill',
  'category' => 'Brando',
  'description' => __( 'Place a counter', 'brando-addons' ),
  'icon' => 'fa fa-clock-o brando-shortcode-icon', //URL or CSS class with icon image.
  'params' => array(
    array(
      'type' => 'dropdown',
      'holder' => 'div',
      'class' => '',
      'heading' => __('Counter Style', 'brando-addons'),
      'param_name' => 'counter_or_chart',
      'value' => array(__('Select Counter Style', 'brando-addons') => '',
                       __('Counter Style1', 'brando-addons') => 'counter-style1',
                       __('Counter Style2', 'brando-addons') => 'counter-style2',
                       __('Counter Style3', 'brando-addons') => 'counter-style3',
                      ),
    ),
    array(
      'type' => 'brando_preview_image',
      'heading' => __('Select pre-made style', 'brando-addons'),
      'param_name' => 'brando_counter_skill_preview_image',
      'admin_label' => true,
      'value' => array(__('Select Counter or Skill', 'brando-addons') => '',
                        __('Counter Style1', 'brando-addons') => 'counter-style1',
                        __('Counter Style2', 'brando-addons') => 'counter-style2',
                        __('Counter Style3', 'brando-addons') => 'counter-style3',
                      ),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'heading' => __('Custom Icon', 'brando-addons'),
      'param_name' => 'custom_icon',
      'value' => array(__('NO', 'brando-addons') => '0',
                       __('YES', 'brando-addons') => '1'
                      ),
      'dependency'  => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2') ),
    ),
    array(
      'type' => 'attach_image',
      'heading' => __('Custom Icon Image', 'brando-addons'),
      'param_name' => 'custom_icon_image',
      'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
      'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'brando-addons' ),
    ),
    array(
      'type' => 'brando_icon',
      'heading' => __('Select Counter Icon', 'brando-addons'),
      'param_name' => 'counter_icon',
      'admin_label' => true,
      'value' => '',
      'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
    ),
    array(
      'type' => 'textfield',
      'heading' =>__('Counter Number', 'brando-addons'),
      'param_name' => 'counter_number',
      'admin_label' => true,
      'dependency'  => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
    ),
    array(
      'type' => 'textfield',
      'heading' => __('Title', 'brando-addons'),
      'param_name' => 'title',
      'admin_label' => true,
      'dependency'  => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
    ),
    array(
      'type' => 'brando_custom_switch_option',
      'heading' => __('Show Separator', 'brando-addons'),
      'param_name' => 'brando_show_separator',
      'value' => array(__('No', 'brando-addons') => '0', 
                       __('Yes', 'brando-addons') => '1'
                      ),
      'description' => __( 'Select YES to show Separator', 'brando-addons' ),
      'dependency'  => array( 'element' => 'counter_or_chart', 'value' => array('counter-style3'))
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Separator Color', 'brando-addons' ),
      'param_name' => 'brando_sep_color',
      'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
      'group' => 'Configuration',
    ),  
    array(
      'type' => 'textfield',
      'heading' => __('Separator Height', 'brando-addons' ),
      'param_name' => 'separator_height',
      'dependency' => array( 'element' => 'brando_show_separator', 'value' => array('1') ),
      'description' => __( 'Define custom separator height in px like 2px', 'brando-addons' ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Counter Number style', 'brando-addons'),
      'param_name' => 'counter_number_style',
      'admin_label' => true,
      'value' => array(__('Default', 'brando-addons') => '',
                       __('White','brando-addons') => 'white-text',
                       __('Black','brando-addons') => 'black-text',
                       __('Custom Color','brando-addons') => 'custom',
                      ),
      'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Counter Number Color', 'brando-addons' ),
      'param_name' => 'counter_number_color',
      'dependency' => array( 'element' => 'counter_number_style', 'value' => array('custom') ),
      'description' => __( 'Specify counter number color', 'brando-addons' ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Icon Size', 'brando-addons'),
      'param_name' => 'counter_icon_size',
      'admin_label' => true,
      'value' => array( __('Default','brando-addons') => '',
                        __('Extra Large','brando-addons') => 'icon-extra-large', 
                        __('Large','brando-addons') => 'icon-large',
                        __('Medium','brando-addons') => 'icon-medium',
                        __('Small','brando-addons') => 'icon-small',
                        __('Extra Small','brando-addons') => 'icon-extra-small',
                      ),
      'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2') ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Title Style','brando-addons'),
      'param_name' => 'title_style',
      'admin_label' => true,
      'value' => array(__('Default','brando-addons') => '',
                       __('White','brando-addons') => 'white-text',
                       __('Black','brando-addons') => 'black-text',
                       __('Custom Color', 'brando-addons') => 'custom',
                      ),
      'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Title Color', 'brando-addons' ),
      'param_name' => 'title_color',
      'dependency' => array( 'element' => 'title_style', 'value' => array('custom') ),
      'description' => __( 'Specify title color', 'brando-addons' ),
      'group' => 'Configuration',
    ),
    array(
      'type' => 'colorpicker',
      'class' => '',
      'heading' => __( 'Icon Color', 'brando-addons' ),
      'param_name' => 'icon_color',
      'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2') ),
      'group' => 'Configuration',
    ),
    array(
        'type'        => 'responsive_font_settings',
        'param_name'  => 'title_settings',
        'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
        'group' => 'Font Settings',
        'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
    ),
    array(
        'type'        => 'responsive_font_settings',
        'param_name'  => 'counter_settings',
        'heading'     => esc_html__( 'Font Settings Counter Number', 'hcode-addons' ),
        'group' => 'Font Settings',
        'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
        'hide_font_settings_element_lg' => array('text-align','font-transform'),
        'hide_font_settings_element_md' => array('text-align','font-transform'),
        'hide_font_settings_element_sm' => array('text-align','font-transform'),
        'hide_font_settings_element_xs' => array('text-align','font-transform'),
    ),
    array(
      'type' => 'dropdown',
      'param_name' => 'brando_row_animation_style',
      'heading' => __('Animation Style', 'brando-addons' ),
      'value' => brando_animation_style(),
      'group' => 'Animation',
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Data Duration Time', 'brando-addons'),
      'param_name' => 'counter_animation_duration',
      'admin_label' => true,
      'value' => array(__('Default', 'brando-addons') => '',
                       __('1000ms', 'brando-addons') => '1000', 
                       __('2000ms', 'brando-addons') => '2000',
                       __('3000ms', 'brando-addons') => '3000',
                       __('4000ms', 'brando-addons') => '4000',
                       __('5000ms', 'brando-addons') => '5000',
                       __('6000ms', 'brando-addons') => '6000',
                       __('7000ms', 'brando-addons') => '7000',
                      ),
      'std' => '7000',
      'dependency' => array( 'element' => 'counter_or_chart', 'value' => array('counter-style1','counter-style2','counter-style3') ),
        
    ),
    array(
      'type' => 'dropdown',
      'heading' => __('Custom Image Size', 'brando-addons'),
      'param_name' => 'brando_custom_image_srcset',
      'value' => brando_image_size(),
      'std' => 'full',
      'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
      'group' => 'Image',
    ),
    $brando_vc_extra_id,
    $brando_vc_extra_class,
    ),
  ) 
);